(function(g){var window=this;'use strict';var VW=function(F){F.publish("cardstatechange",F.AD()&&F.U0()?1:0)},P_=function(F,J){var b=g.ca(J),I=b?J:arguments;
for(b=b?0:1;b<I.length;b++){if(F==null)return;F=F[I[b]]}return F},awR=function(F){var J=g.zv(F);
F=g.fL(F);return new g.uu(J.x,J.y,F.width,F.height)},elU=function(F,J,b){var I=I===void 0?{}:I;
var u;return u=g.l8(F,J,function(){g.fw(u);b.apply(F,arguments)},I)},rH=function(F){F=g.n3(F);
delete B_[F];g.Vj(B_)&&Tz&&Tz.stop()},po8=function(){Tz||(Tz=new g.ty(function(){KCH()},20));
var F=Tz;F.isActive()||F.start()},KCH=function(){var F=g.L3();
g.ie(B_,function(J){g4U(J,F)});
g.Vj(B_)||po8()},S_=function(F,J,b,I){g.vV.call(this);
if(!Array.isArray(F)||!Array.isArray(J))throw Error("Start and end parameters must be arrays");if(F.length!=J.length)throw Error("Start and end points must be the same length");this.U=F;this.V=J;this.duration=b;this.D=I;this.coords=[];this.progress=this.W=0;this.Z=null},g4U=function(F,J){J<F.startTime&&(F.endTime=J+F.endTime-F.startTime,F.startTime=J);
F.progress=(J-F.startTime)/(F.endTime-F.startTime);F.progress>1&&(F.progress=1);F.W=1E3/(J-F.Z);F.Z=J;mXV(F,F.progress);F.progress==1?(F.C=0,rH(F),F.onFinish(),F.ly()):F.isPlaying()&&F.Xv()},mXV=function(F,J){typeof F.D==="function"&&(J=F.D(J));
F.coords=Array(F.U.length);for(var b=0;b<F.U.length;b++)F.coords[b]=(F.V[b]-F.U[b])*J+F.U[b]},yxb=function(F,J){g.SX.call(this,F);
this.coords=J.coords;this.x=J.coords[0];this.y=J.coords[1];this.z=J.coords[2];this.duration=J.duration;this.progress=J.progress;this.fps=J.W;this.state=J.C},sc=function(F,J,b,I,u){S_.call(this,J,b,I,u);
this.element=F},iGU=function(F,J,b,I,u){if(J.length!=2||b.length!=2)throw Error("Start and end points must be 2D");
sc.call(this,F,J,b,I,u)},zl5=function(F){return Math.pow(F,3)},N4b=function(F){return 3*F*F-2*F*F*F},lwk=function(F){g.R.call(this);
this.U=F||window;this.C=[]},Yl=function(F){return F.baseUrl||null},$l=function(F,J){return g.qN(g.EG(F,J),function(b){return!!b})},fwU=function(F,J,b){function I(AJ){var F7=AJ.hovercardButton;
if(!F7)return null;F7=F7.subscribeButtonRenderer;if(!F7)return null;var h=w(F7.unsubscribedButtonText),L=w(F7.subscribedButtonText);if(F7.subscribed){var l=w(F7.subscriberCountWithUnsubscribeText);var c=w(F7.subscriberCountText)}else l=w(F7.subscriberCountText),c=w(F7.subscriberCountWithSubscribeText);var Da=null;if(AJ.signinEndpoint){Da=P_(AJ,"signinEndpoint","webNavigationEndpointData","url");if(!Da){var fz,Kz;Da=(Kz=g.O((fz=F7.signInEndpoint)==null?void 0:fz.commandMetadata,g.Nm))==null?void 0:
Kz.url}if(!Da)return null}return h&&(L||Da)?{subscribed:F7.subscribed,subscribeText:h,subscribeCount:l,unsubscribeText:L,unsubscribeCount:c,enabled:F7.enabled,signinUrl:Da,classic:AJ.useClassicSubscribeButton}:null}
function u(AJ){if(AJ){var F7=[],h=AJ.videoId;h&&F7.push("v="+h);(h=AJ.playlistId)&&F7.push("list="+h);(AJ=AJ.startTimeSeconds)&&F7.push("t="+AJ);return"/watch?"+F7.join("&")}}
function w(AJ){if(!AJ)return null;var F7=AJ.simpleText;return F7?F7:AJ.runs?g.EG(AJ.runs,function(h){return h.text}).join(""):null}
J=J.endscreenElementRenderer;if(!J)return null;var M=J.style,q=J.endpoint||{},v=null,a=null,e=!1,K=null,p=null,m=null,y=null,f=!1,d=null,G=null,P=null,r=null,Q=null,D=null;if(M==="VIDEO")g.O(q,g.S0)?v=g.O(q,g.S0).url:(D=g.O(q,g.x$),v=u(D)),a=!1,K=F,J.thumbnailOverlays?(e=J.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,p=w(e.text),e=e.style==="LIVE"):p=w(J.videoDuration);else if(M==="PLAYLIST")g.O(q,g.S0)?v=g.O(q,g.S0).url:(D=g.O(q,g.x$),v=u(D)),a=!1,K=F,m=w(J.playlistLength);else if(M===
"CHANNEL"){if(f=P_(q,"browseEndpoint","browseId"))y=f,v="/channel/"+y;a=!1;K="new";(f=!!J.isSubscribe)?d=I(J):G=w(J.subscribersText)}else M==="WEBSITE"?((P=P_(q,"urlEndpoint","url"))&&(v=P),a=!0,K="new",P=J.icon.thumbnails[0].url):M==="CREATOR_MERCHANDISE"&&(J.productPrice&&(r=w(J.productPrice)),J.additionalFeesText&&(Q=w(J.additionalFeesText)),(a=P_(q,"urlEndpoint","url"))&&(v=a),a=!0,K="new");F=P_(J,"title","accessibility","accessibilityData","label");var t=J.endpoint?J.endpoint.clickTrackingParams:
null,n="";if(J.metadata){var uk=w(J.metadata);uk&&(n=uk)}return{id:"element-"+b,type:M,title:w(J.title),metadata:n,callToAction:w(J.callToAction),m9:J.image,iconUrl:P,left:Number(J.left),width:Number(J.width),top:Number(J.top),aspectRatio:Number(J.aspectRatio),startMs:Math.floor(Number(J.startMs)),endMs:Math.floor(Number(J.endMs)),videoDuration:p,uV:e,playlistLength:m,channelId:y,subscribeButton:d,subscribersText:G,isSubscribe:f,targetUrl:v||null,JzI:a,sessionData:t?{itct:t}:null,DER:K,RU:F?F:null,
isPlaceholder:J.isPlaceholder,impressionUrls:$l(J.impressionUrls||[],Yl),QIG:$l(J.hovercardShowUrls||[],Yl),clickUrls:$l(q.loggingUrls||[],Yl),visualElement:g.NY(J.trackingParams),productPrice:r,additionalFeesText:Q,watchEndpoint:D||null}},WCH=function(F,J){var b={startMs:Math.floor(Number(F.startMs)),
impressionUrls:$l(F.impressionUrls||[],Yl),elements:$l(F.elements||[],function(I,u){return fwU(J,I,u)})};
F.trackingParams&&(b.visualElement=g.NY(F.trackingParams));return b},dXt=function(F){g.GN.call(this,F);
this.Z=this.endscreen=null;this.U={};this.W={};this.D=this.T=null;this.Y=[];this.C=null;this.Tj=!0;this.V=0;F=F.J();this.N=g.Bu(F)||g.rN(F);this.events=new g.s5(this);g.k(this,this.events);this.events.B(this.player,g.u6("creatorendscreen"),this.onCueRangeEnter);this.events.B(this.player,g.wq("creatorendscreen"),this.onCueRangeExit);this.events.B(this.player,"resize",this.mO);this.events.B(window,"focus",this.AeW);this.load();var J=g.H1("STYLE");(g.D8("HEAD")[0]||document.body).appendChild(J);this.addOnDisposeCallback(function(){g.ID(J)});
J.sheet&&(J.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),J.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},E4V=function(F){return F.player.getVideoData().T0?"current":F.N?"new":"current"},Ct=function(F){return F.player.J().playerStyle==="creator-endscreen-editor"},jMb=function(F){var J=F.player.getVideoData(),b=J.videoId;
F.Z&&F.Z.abort();b={method:"POST",onFinish:function(u){var w=F.Z=null;u.status===200&&(u=u.responseText,u.substring(0,3)===")]}"&&(u=u.substring(3),w=JSON.parse(u),w=WCH(w,E4V(F))));X2(F,w)},
urlParams:{v:b},withCredentials:!0};F.N&&(b.urlParams.ptype="embedded");var I=J.uK;I&&(b.postParams={ad_tracking:I});if(J=g.Jc_(J))if(J=g.Ty(J),J=g.VG(J))F.Z=g.E6(J,b)},X2=function(F,J,b){b=b===void 0?!0:b;
F.player.Yo("creatorendscreen");F.T&&(F.T.dispose(),F.T=null,F.D.dispose(),F.D=null);for(var I=g.N(Object.values(F.U)),u=I.next();!u.done;u=I.next())u.value.dispose();F.U={};F.W={};F.Y.length>0&&(F.Y.forEach(function(q){q.dispose()}),F.Y.length=0);
F.C&&(g.Mr(F.C,"ytp-ce-element-show"),F.C.setAttribute("aria-hidden","true"));F.V=0;if((F.endscreen=J)&&J.elements){b&&Gbe(F);b=[];I=new g.b6(J.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});b.push(I);F.player.J().U||(F.T=new g.U({X:"div",K:"ytp-ce-shadow"}),g.Pp(F.player,F.T.element,4),F.D=new g.ZU(F.T,200));for(I=0;I<J.elements.length;++I){u=J.elements[I];var w=VDt(F,u);if(w){F.U[u.id]=w;F.W[u.id]=u;g.Pp(F.player,w.element,4);var M=new g.b6(u.startMs,u.endMs,{id:"ytp-ce-element-"+
u.id,namespace:"creatorendscreen"});b.push(M);PPH(F,w,u)}else g.rQ(new g.hC("buildEndscreenElement null",u))}F.player.TU(b);F.mO()}},Gbe=function(F){var J=g.fO(),b=g.W8();
b&&J&&F.endscreen.visualElement&&g.tE(g.oO)(void 0,b,J,F.endscreen.visualElement)},VDt=function(F,J){var b=null;
switch(J.type){case "VIDEO":F={X:"div",Dv:["ytp-ce-element","ytp-ce-video"],L:{tabindex:"0","aria-label":J.RU||"","aria-hidden":"true"},j:[{X:"div",K:"ytp-ce-element-shadow"},{X:"div",K:"ytp-ce-covering-image",L:QW(J)},{X:"div",K:"ytp-ce-covering-shadow-top"},{X:"a",K:"ytp-ce-covering-overlay",L:{href:Rq(F,J.targetUrl),tabindex:"-1"},j:[{X:"div",Dv:["ytp-ce-video-title","ytp-webkit-ellipsis"],L:{dir:g.gD(J.title||"")},sQ:J.title},{X:"div",K:J.uV?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
sQ:J.videoDuration||void 0}]}]};b=new g.U(F);break;case "PLAYLIST":F={X:"div",Dv:["ytp-ce-element","ytp-ce-playlist"],L:{tabindex:"0","aria-label":J.RU||"","aria-hidden":"true"},j:[{X:"div",K:"ytp-ce-element-shadow"},{X:"div",K:"ytp-ce-covering-image",L:QW(J)},{X:"div",K:"ytp-ce-covering-shadow-top"},{X:"a",K:"ytp-ce-covering-overlay",L:{href:Rq(F,J.targetUrl),tabindex:"-1"},j:[{X:"div",Dv:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],L:{dir:g.gD(J.title||"")},sQ:J.title},{X:"div",K:"ytp-ce-playlist-count",
j:[{X:"div",K:"ytp-ce-playlist-icon"},{X:"div",K:"ytp-ce-playlist-count-text",sQ:J.playlistLength||void 0}]}]}]};b=new g.U(F);break;case "CHANNEL":b={X:"div",Dv:["ytp-ce-element","ytp-ce-channel",J.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],L:{tabindex:"0","aria-label":J.RU||"","aria-hidden":"true"},j:[{X:"div",K:"ytp-ce-element-shadow"},{X:"div",K:"ytp-ce-expanding-overlay",j:[{X:"div",K:"ytp-ce-expanding-overlay-hider"},{X:"div",K:"ytp-ce-expanding-overlay-background"},{X:"div",K:"ytp-ce-expanding-overlay-content",
j:[{X:"div",K:"ytp-ce-expanding-overlay-body",j:[{X:"div",K:"ytp-ce-expanding-overlay-body-padding",j:[{X:"a",Dv:["ytp-ce-channel-title","ytp-ce-link"],L:{href:Rq(F,J.targetUrl),target:"_blank",tabindex:"-1",dir:g.gD(J.title||"")},sQ:J.title},J.subscribeButton?{X:"div",K:"ytp-ce-subscribe-container",j:[{X:"div",K:"ytp-ce-channel-subscribe"}]}:"",J.subscribersText?{X:"div",K:"ytp-ce-channel-subscribers-text",sQ:J.subscribersText}:"",J.metadata?{X:"div",Dv:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],sQ:J.metadata}:""]}]}]}]},{X:"div",K:"ytp-ce-expanding-image",L:QW(J)}]};b=new g.U(b);var I=g.Oa(document,"div","ytp-ce-channel-subscribe",b.element)[0];if(J.subscribeButton&&J.channelId){g.uG(I,"ytp-ce-subscribe-button");if(F.player.J().U){var u=null;var w=J.sessionData.itct}else u="endscreen",w=null;u=new g.Aq(J.subscribeButton.subscribeText,J.subscribeButton.subscribeCount,J.subscribeButton.unsubscribeText,J.subscribeButton.unsubscribeCount,!!J.subscribeButton.enabled,!!J.subscribeButton.classic,
J.channelId,!!J.subscribeButton.subscribed,u,w,F.player,!1);I.appendChild(u.element);F.Y.push(u)}break;case "WEBSITE":F={X:"div",Dv:["ytp-ce-element","ytp-ce-website"],L:{tabindex:"0","aria-label":J.RU||"","aria-hidden":"true"},j:[{X:"div",K:"ytp-ce-element-shadow"},{X:"div",K:"ytp-ce-expanding-overlay",j:[{X:"div",K:"ytp-ce-expanding-overlay-hider"},{X:"div",K:"ytp-ce-expanding-overlay-background"},{X:"div",K:"ytp-ce-expanding-overlay-content",j:[{X:"div",K:"ytp-ce-expanding-overlay-body",j:[{X:"div",
K:"ytp-ce-expanding-overlay-body-padding",j:[{X:"div",K:"ytp-ce-website-title",L:{dir:g.gD(J.title||"")},sQ:J.title},{X:"div",K:"ytp-ce-website-metadata",sQ:J.metadata},{X:"a",Dv:["ytp-ce-website-goto","ytp-ce-link"],L:{href:Rq(F,J.targetUrl),target:"_blank",tabindex:"-1"},sQ:J.callToAction}]}]}]}]},{X:"div",K:"ytp-ce-expanding-image",L:QW(J)},{X:"div",K:"ytp-ce-expanding-icon",L:B4m(J.iconUrl)}]};b=new g.U(F);break;case "CREATOR_MERCHANDISE":b="",J.productPrice&&(b={X:"div",K:"ytp-ce-merchandise-price-container",
j:[{X:"div",K:"ytp-ce-merchandise-price",sQ:J.productPrice}]},J.additionalFeesText&&b.j.push({X:"div",K:"ytp-ce-merchandise-additional-fees",sQ:J.additionalFeesText})),F={X:"div",Dv:["ytp-ce-element","ytp-ce-merchandise"],L:{tabindex:"0","aria-label":J.RU||"","aria-hidden":"true"},j:[{X:"div",K:"ytp-ce-element-shadow"},{X:"div",K:"ytp-ce-expanding-overlay",j:[{X:"div",K:"ytp-ce-expanding-overlay-hider"},{X:"div",K:"ytp-ce-expanding-overlay-background"},{X:"div",K:"ytp-ce-expanding-overlay-content",
j:[{X:"div",K:"ytp-ce-expanding-overlay-body",j:[{X:"div",K:"ytp-ce-expanding-overlay-body-padding",j:[{X:"div",K:"ytp-ce-merchandise-title",L:{dir:g.gD(J.title||"")},sQ:J.title},b,{X:"div",K:"ytp-ce-merchandise-metadata",sQ:J.metadata},{X:"a",Dv:["ytp-ce-merchandise-goto","ytp-ce-link"],L:{href:Rq(F,J.targetUrl),target:"_blank",tabindex:"-1"},sQ:J.callToAction}]}]}]}]},{X:"div",K:"ytp-ce-expanding-image",L:QW(J)},{X:"div",K:"ytp-ce-merchandise-invideo-cta-container",j:[{X:"div",K:"ytp-ce-merchandise-invideo-cta",
sQ:J.callToAction||void 0}]}]},b=new g.U(F)}J.isPlaceholder&&g.uG(b.element,"ytp-ce-placeholder");return b},QW=function(F){if(F.m9)var J=F.m9.thumbnails;
return B4m(J?J[J.length-1].url:null)},B4m=function(F){return F?{style:"background-image: url("+F+")"}:{}},PPH=function(F,J,b){function I(v){v&&(J.listen("blur",function(){v.style.display!="none"&&F.Tj&&v.focus()}),J.B(v,"focus",w),J.B(v,"blur",M))}
function u(v){F.V+=v;F.V>0?(g.uG(J.element,"ytp-ce-force-expand"),Ds(F,b.id,!0)):(g.Mr(J.element,"ytp-ce-force-expand"),g.Mr(J.element,"ytp-ce-element-hover"),Ds(F,b.id,!1))}
function w(){u(1)}
function M(){u(-1)}
J.listen("mouseenter",function(){T4L(F,J,b)});
J.listen("mouseleave",function(){rxL(F,J,b)});
F.player.J().U||J.listen("click",function(){g.uG(J.element,"ytp-ce-element-hover")});
J.listen("click",function(v){Sqt(F,b,v)});
J.listen("keypress",function(v){Sqt(F,b,v)});
J.listen("focus",function(){T4L(F,J,b)});
J.listen("blur",function(){rxL(F,J,b)});
J.listen("touchstart",function(){T4L(F,J,b)});
var q=g.c1("ytp-ce-expanding-overlay-hider",J.element);q&&J.B(q,"touchstart",function(v){v.stopPropagation();g.Mr(J.element,"ytp-ce-element-hover");g.Mr(J.element,"ytp-ce-force-expand")});
J.listen("keydown",function(v){F.Tj=v.keyCode===9&&!v.shiftKey});
I(g.c1("ytp-sb-subscribe",J.element));I(g.c1("ytp-sb-unsubscribe",J.element));J.listen("focus",w);J.listen("blur",M)},Sqt=function(F,J,b){if(J.targetUrl&&(!b||b.type!=="keypress"||b.keyCode===13)){for(var I=b.target;I&&!g.I3(I,"ytp-ce-element");){g.I3(I,"subscribe-label")&&sML(F,J);
if(g.I3(I,"ytp-ce-channel-subscribe"))return;I=I.parentElement||null}if(!I||g.I3(I,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(I=F.U[J.id])rxL(F,I,J),I.element.blur();if(b.ctrlKey||b.metaKey||J.DER==="new")sML(F,J),F.player.sendVideoStatsEngageEvent(17,void 0),F.player.pauseVideo(),b=g.Ty(Rq(F,J.targetUrl)),b=g.VG(b),g.RJ(b,void 0,J.sessionData);else{var u=g.hP(F.player.J())||F.player.getVideoData().T0,w=function(){var M=Rq(F,J.targetUrl),q=J.sessionData,v=J.watchEndpoint,a=
g.bi(M);u&&a&&(a.v||a.list)?F.player.yp(a.v,q,a.list,!1,void 0,v||void 0):g.Qm(M,q)};
sML(F,J,function(){F.player.sendVideoStatsEngageEvent(17,w)})}}}},Rq=function(F,J){F=F.player.J();
if(J){if(J.startsWith("//"))return F.protocol+":"+J;if(J.startsWith("/"))return g.Hu(F)+J}else return"";return J},T4L=function(F,J,b){g.I3(J.element,"ytp-ce-element-hover")||(b.type==="VIDEO"||b.type==="PLAYLIST"?g.uG(J.element,"ytp-ce-element-hover"):F.player.J().U?(new g.ty(function(){g.uG(J.element,"ytp-ce-element-hover")},200)).start():g.uG(J.element,"ytp-ce-element-hover"),kl(F,b.QIG),Ds(F,b.id,!0))},rxL=function(F,J,b){g.Mr(J.element,"ytp-ce-element-hover");
g.Mr(J.element,"ytp-ce-force-expand");Ds(F,b.id,!1)},Ds=function(F,J,b){F.T&&(b?F.D.show():F.D.hide());
for(var I=g.N(Object.keys(F.U)),u=I.next();!u.done;u=I.next())u=u.value,u!==J&&g.qr(F.U[u].element,"ytp-ce-element-shadow-show",b)},kl=function(F,J,b){function I(){w||(u++,u===J.length&&(M.stop(),b&&b()))}
if(!J||J.length===0||Ct(F))b&&b();else{J=YqU(F,J);var u=0,w=!1,M=new g.ty(function(){w=!0;b&&b()},1E3,F);
M.start();for(F=0;F<J.length;F++)g.Xp(J[F],I)}},sML=function(F,J,b){kl(F,J.clickUrls,b);
(F=g.W8())&&J.JzI&&g.Jr(F,J.visualElement)},YqU=function(F,J){var b=F.player.getVideoData().clientPlaybackNonce;
F=F.player.getCurrentTime().toFixed(2);b={CPN:b,AD_CPN:b,MT:F};F=[];for(var I=0;I<J.length;I++)F.push($XH(J[I],b));return F},$XH=function(F,J){return F.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(b){var I=unescape(b);
I=I.substring(1,I.length-1);return J[I]?escape(J[I]):b})},CP1=function(F){return typeof F==="string"?F:""},Oc=function(F,J,b){for(var I in J)if(J[I]===F)return F;
return b},XoV=function(F,J,b,I){this.value=F;
this.target=J;this.showLinkIcon=b;this.C=I},oq=function(F){return F.value?F.value:null},h0=function(F){if(!F)return null;
var J=g.Ty(CP1(F.value));J=g.VG(J);if(!J)return null;var b=Oc(F.target,QMm,"current");if(b==null)F=null;else{var I=F.show_link_icon;F=new XoV(J,b,I==="true"||I==="false"?I==="true":!0,F.pause_on_navigation!=null?F.pause_on_navigation:!0)}return F},Rle=function(F,J,b){this.type=F;
this.trigger=J;this.url=b},OGW=function(F){if(!F)return null;
var J=Oc(F.type,DXL),b=Oc(F.trigger,kbz);F=F.url;F=Array.isArray(F)&&F.length?F[0]:F;F=h0(F?F:null);return J?new Rle(J,b,F):null},o4R=function(F,J,b,I,u){this.id=F;
this.type=J;this.style=b;this.data=u;this.action=I||[]},hle=function(F,J){return g.xL(F.action,J)},cxt=function(F,J){this.context=F;
this.C=J},UXk=function(F){return F.customMessage?c_("div","iv-card-message",F.customMessage):""},Uc=function(F,J){F="background-image: url("+F+");";
var b=[];J&&b.push(J);return{X:"div",K:"iv-card-image",L:{style:F},j:b}},xXb=function(F){if(!F.metaInfo||F.metaInfo.length===0)return"";
var J=[];F=g.N(F.metaInfo);for(var b=F.next();!b.done;b=F.next())J.push(c_("li","",b.value));return{X:"ul",K:"iv-card-meta-info",j:J}},c_=function(F,J,b){J?typeof J==="string"?J={"class":J}:Array.isArray(J)&&(J={"class":J.join(" ")}):J={};
J.dir=g.gD(b);return{X:F,L:J,sQ:b}},n4z=function(F){if(!F.customMessage)return"";
var J=["iv-card-action","iv-card-primary-link"],b={};F.QP&&(J.push("iv-card-action-icon"),b.style="background-image: url("+F.QP+");");b.dir=g.gD(F.customMessage);var I=[{X:"span",sQ:F.customMessage}];F.showLinkIcon&&(I.push("\u00a0"),I.push({X:"span",K:"iv-card-link-icon"}));return{X:"div",Dv:J,L:b,j:I}},xl=function(F,J,b,I){if(I){J=g.N(J);
for(var u=J.next();!u.done;u=J.next())F.C(u.value,I,b.id,b.sessionData,b.dg.click,5)}},tDt=function(F,J){this.merchant=F;
this.price=J},ZGk=function(F){var J;
(J=F)&&!(J=F.length>1?F.charAt(0)==="/"&&F.charAt(1)!=="/":F==="/")&&(J=F.replace(/^(https?:)?\/\//,"").split("/",1),J=!J||J.length<1||!J[0]?[]:J[0].toLowerCase().split(".").reverse(),J=J[0]==="com"&&J[1]==="youtube"||J[0]==="be"&&J[1]==="youtu");return J?F.indexOf("/redirect?")===-1:!1},HGz=function(F,J){return J?J:ZGk(F)?"current":"new"},nt=function(F,J){g.R.call(this);
var b=this;this.element=F;this.context=J;this.bR=!1;this.KW=new Map;this.Jz=new Map;this.context.G.addEventListener(g.u6("annotations_module"),function(I){(I=b.KW.get(I))&&I.apply(b)});
this.context.G.addEventListener(g.wq("annotations_module"),function(I){(I=b.Jz.get(I))&&I.apply(b)})},t0=function(F,J,b,I,u,w,M){F.context.C.listen(J,"click",function(q){F.sE(b,I,u,w||[],M||0,q)});
F.context.C.listen(J,"touchstart",function(){F.bR=!1});
F.context.C.listen(J,"touchmove",function(){F.bR=!0})},LC1=function(F){var J;
return((J=g.O(F,g.S0))==null?0:J.url)?g.O(F,g.S0).url:(F=g.O(F,g.x$))&&F.videoId?(J="/watch?v="+F.videoId,F.playlistId&&(J+="&list="+F.playlistId),F.index&&(J+="&index="+F.index),F.startTimeSeconds&&(J+="&t="+F.startTimeSeconds),J):null},Zs=function(F,J,b){return{Hr:(F.impressionLoggingUrlsV2s||[]).map(function(I){return I.baseUrl||""}),
click:(b.loggingUrls||[]).map(function(I){return I.baseUrl||""}),
close:(J.dismissLoggingUrlsV2s||[]).map(function(I){return I.baseUrl||""}),
tL:(J.impressionLoggingUrlsV2s||[]).map(function(I){return I.baseUrl||""}),
HM:(J.clickLoggingUrlsV2s||[]).map(function(I){return I.baseUrl||""})}},FkU=function(F,J,b){nt.call(this,J,b);
var I=this;this.G=F;this.eventId=null;this.Q2=this.qf=this.Om=this.T=this.isInitialized=!1;this.cards=[];this.cN=this.Y=this.fW=this.D=this.zj=this.C=null;this.Tj=[];this.eE=this.V=this.r6=this.WN=null;this.W=0;this.kQ=new g.ty(function(){},b.rD.R5?4E3:3E3);
g.k(this,this.kQ);this.nW=new g.ty(function(){});
g.k(this,this.nW);this.Gj=new cxt(b,function(u,w,M,q,v,a){t0(I,u,w,M,q,v,a)});
this.N=new g.U({X:"div",K:"iv-drawer",L:{id:"iv-drawer"},j:[{X:"div",K:"iv-drawer-header",L:{"aria-role":"heading"},j:[{X:"span",K:"iv-drawer-header-text"},{X:"button",Dv:["iv-drawer-close-button","ytp-button"],L:{"aria-label":"Kartlar\u0131 gizle",tabindex:"0"}}]},{X:"div",K:"iv-drawer-content"}]});g.k(this,this.N);this.Z=this.N.element;this.oI=new g.ZU(this.N,330);g.k(this,this.oI);this.Um=g.c1("iv-drawer-header-text",this.Z);this.U=g.c1("iv-drawer-content",this.Z);this.addCueRange(0,b.videoData.lengthSeconds*
1E3,"",function(){I.Om&&H_(I,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(I.Om=I.T)&&Lt(I)});
this.dD=new g.s5(this);g.k(this,this.dD);this.G.addEventListener("videodatachange",this.xR.bind(this))},JQH=function(F,J){J=J.data;
J.autoOpenMs&&F.addCueRange(J.autoOpenMs,0x8000000000000,"",function(){H_(F,"YOUTUBE_DRAWER_AUTO_OPEN")});
J.autoCloseMs&&F.addCueRange(J.autoCloseMs,0x8000000000000,"",function(){Lt(F)});
var b=J.headerText;g.wK(F.Um,b);F.Y&&F.Y.setAttribute("title",b);J.eventId&&(F.eventId=J.eventId);F.WN=g.NY(J.trackingParams);F.V=g.NY(J.closeTrackingParams);F.r6=g.NY(J.iconTrackingParams)},b5z=function(F,J){var b=J.cardId?J.cardId:"cr:"+F.W,I=F.G.J().experiments.pW("enable_error_corrections_infocard_web_client");
if(!J.content&&J.teaser.simpleCardTeaserRenderer&&I){var u=J.teaser.simpleCardTeaserRenderer,w=J.icon?J.icon.infoCardIconRenderer:null;J={id:b,timestamp:F.W,type:"simple",teaserText:g.Kr(u.message),teaserDurationMs:Number(J.cueRanges[0].teaserDurationMs),startMs:Number(J.cueRanges[0].startCardActiveMs),autoOpen:!!J.autoOpen,sessionData:{},sponsored:!1,dg:{},X2:null,Z2:u.trackingParams?g.NY(u.trackingParams):null,r6:w&&w.trackingParams?g.NY(w.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
QP:null,title:"",customMessage:"",url:null,onClickCommand:u.onTapCommand||null};F3(F,J)}else{var M;if((M=J.content)==null?0:M.simpleCardContentRenderer){if(!J.cueRanges.length)return;w=(u=J.content)==null?void 0:u.simpleCardContentRenderer;u=J.teaser.simpleCardTeaserRenderer;var q=J.icon?J.icon.infoCardIconRenderer:null;J={id:b,timestamp:F.W,type:"simple",teaserText:g.Kr(u.message),teaserDurationMs:Number(J.cueRanges[0].teaserDurationMs),startMs:Number(J.cueRanges[0].startCardActiveMs),autoOpen:!!J.autoOpen,
sessionData:JK(F,b,J,w),sponsored:!1,dg:Zs(w,u,w.command),X2:w.trackingParams?g.NY(w.trackingParams):null,Z2:u.trackingParams?g.NY(u.trackingParams):null,r6:q&&q.trackingParams?g.NY(q.trackingParams):null,imageUrl:bN(w.image.thumbnails,290).url,displayDomain:w.displayDomain?g.Kr(w.displayDomain):null,showLinkIcon:!!w.showLinkIcon,QP:null,title:w.title?g.Kr(w.title):"",customMessage:w.callToAction?g.Kr(w.callToAction):"",url:g.O(w.command,g.S0).url?h0({pause_on_navigation:!F.context.videoData.isLivePlayback,
target:"new",value:g.O(w.command,g.S0).url}):null,onClickCommand:null};F3(F,J)}else{var v;if((v=J.content)==null?0:v.collaboratorInfoCardContentRenderer){if(!J.cueRanges.length)return;u=(w=J.content)==null?void 0:w.collaboratorInfoCardContentRenderer;w=J.teaser.simpleCardTeaserRenderer;q=J.icon?J.icon.infoCardIconRenderer:null;J={id:b,timestamp:F.W,type:"collaborator",teaserText:g.Kr(w.message),teaserDurationMs:Number(J.cueRanges[0].teaserDurationMs),startMs:Number(J.cueRanges[0].startCardActiveMs),
autoOpen:!!J.autoOpen,sessionData:JK(F,b,J,u),sponsored:!1,dg:Zs(u,w,u.endpoint),X2:u.trackingParams?g.NY(u.trackingParams):null,Z2:w.trackingParams?g.NY(w.trackingParams):null,r6:q&&q.trackingParams?g.NY(q.trackingParams):null,channelId:g.O(u.endpoint,g.fY).browseId,customMessage:u.customText?g.Kr(u.customText):null,profileImageUrl:bN(u.channelAvatar.thumbnails,290).url,title:u.channelName?g.Kr(u.channelName):"",metaInfo:[u.subscriberCountText?g.Kr(u.subscriberCountText):""],url:h0({pause_on_navigation:!F.context.videoData.isLivePlayback,
target:"new",value:g.O(u.endpoint,g.fY).canonicalBaseUrl?g.O(u.endpoint,g.fY).canonicalBaseUrl:"/channel/"+g.O(u.endpoint,g.fY).browseId}),onClickCommand:null};F3(F,J)}else{var a;if((a=J.content)==null?0:a.playlistInfoCardContentRenderer){if(!J.cueRanges.length)return;u=(q=J.content)==null?void 0:q.playlistInfoCardContentRenderer;w=J.teaser.simpleCardTeaserRenderer;q=J.icon?J.icon.infoCardIconRenderer:null;J={id:b,timestamp:F.W,type:"playlist",teaserText:g.Kr(w.message),teaserDurationMs:Number(J.cueRanges[0].teaserDurationMs),
startMs:Number(J.cueRanges[0].startCardActiveMs),autoOpen:!!J.autoOpen,sessionData:JK(F,b,J,u),sponsored:!1,dg:Zs(u,w,u.action),X2:u.trackingParams?g.NY(u.trackingParams):null,Z2:w.trackingParams?g.NY(w.trackingParams):null,r6:q&&q.trackingParams?g.NY(q.trackingParams):null,Kf:bN(u.playlistThumbnail.thumbnails,258).url,customMessage:u.customMessage?g.Kr(u.customMessage):null,playlistVideoCount:g.Kr(u.playlistVideoCount),title:u.playlistTitle?g.Kr(u.playlistTitle):"",metaInfo:[u.channelName?g.Kr(u.channelName):
"",u.videoCountText?g.Kr(u.videoCountText):""],url:h0({pause_on_navigation:!F.context.videoData.isLivePlayback,target:"new",value:LC1(u.action)}),onClickCommand:null};F3(F,J)}else{var e;if((e=J.content)==null?0:e.videoInfoCardContentRenderer){if(!J.cueRanges.length)return;var K;u=(K=J.content)==null?void 0:K.videoInfoCardContentRenderer;w=J.teaser.simpleCardTeaserRenderer;q=J.icon?J.icon.infoCardIconRenderer:null;J={id:b,timestamp:F.W,type:"video",teaserText:g.Kr(w.message),teaserDurationMs:Number(J.cueRanges[0].teaserDurationMs),
startMs:Number(J.cueRanges[0].startCardActiveMs),autoOpen:!!J.autoOpen,sessionData:JK(F,b,J,u),sponsored:!1,dg:Zs(u,w,u.action),X2:u.trackingParams?g.NY(u.trackingParams):null,Z2:w.trackingParams?g.NY(w.trackingParams):null,r6:q&&q.trackingParams?g.NY(q.trackingParams):null,Kf:bN(u.videoThumbnail.thumbnails,258).url,videoDuration:u.lengthString?g.Kr(u.lengthString):null,customMessage:u.customMessage?g.Kr(u.customMessage):null,title:u.videoTitle?g.Kr(u.videoTitle):"",metaInfo:[u.channelName?g.Kr(u.channelName):
"",u.viewCountText?g.Kr(u.viewCountText):""],isLiveNow:!!u.badge,url:h0({pause_on_navigation:!F.context.videoData.isLivePlayback,target:"new",value:LC1(u.action)}),onClickCommand:null};F3(F,J)}}}}}F.W++},bN=function(F,J){for(var b=-1,I=-1,u=0;u<F.length;u++){if(F[u].height===J||F[u].width===290)return F[u];
((F[u].height||0)<J||(F[u].width||0)<290)&&(b<0||(F[b].height||0)<(F[u].height||0)||(F[b].width||0)<(F[u].width||0))?b=u:((F[u].height||0)>=J||(F[u].width||0)>=290)&&(I<0||(F[I].height||0)>(F[u].height||0)||(F[I].width||0)>(F[u].width||0))&&(I=u)}return F[I>=0?I:b]},JK=function(F,J,b,I){return{feature:b.feature?b.feature:"cards",
src_vid:F.context.videoData.videoId,annotation_id:J,ei:F.context.videoData.eventId||"",itct:I.trackingParams||""}},uvt=function(F,J){if(J=IiV(F,J))J===F.C&&(F.C=null),F.G.removeCueRange(J.aH.id),g.ID(J.Ej),g.Hk(F.cards,J),F.w2(),IC(F)},H_=function(F,J,b){if(!F.T){F.oI.show();
F.zj=new g.ty(function(){g.uG(F.context.G.getRootNode(),g.QA.IV_DRAWER_OPEN)},0);
F.zj.start();F.dD.B(F.U,"mousewheel",function(M){F.kQ.start();M.preventDefault();M=M||window.event;var q=0;M.type=="MozMousePixelScroll"?q=0==(M.axis==M.HORIZONTAL_AXIS)?M.detail:0:window.opera?q=M.detail:q=M.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?M.wheelDeltaY/-30:M.wheelDeltaY/-1.2:M.wheelDelta/-1.6:M.wheelDeltaY/-3;if(M=q)F.U.scrollTop+=M});
F.T=!0;var I=g.W8();I&&F.WN&&F.V&&g.LO(I,[F.WN,F.V]);J={TRIGGER_TYPE:J};for(var u=g.N(F.cards),w=u.next();!w.done;w=u.next())w=w.value,w.Sx||(w.Sx=!0,w9U(F.context.logger,w.aH.dg.Hr,J)),I&&g.LO(I,[w.aH.X2]);VW(F.G);b&&(F.D=new g.ty(function(){F.fW=F.Y;F.cN.focus()},330),F.D.start())}},Lt=function(F){F.T&&(F.oI.hide(),g.Ve(F.dD),g.Mr(F.context.G.getRootNode(),g.QA.IV_DRAWER_OPEN),F.T=!1,VW(F.G),F.D&&F.D.stop(),F.D=new g.ty(function(){F.fW&&(F.fW.focus(),F.fW=null)},330),F.D.start())},Mpb=function(F){g.wD(F.Pb(),
[g.QA.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.Pp(F.G,F.Z,5);F.tj();F.Y=g.c1("ytp-cards-button",F.G.getRootNode());F.cN=g.c1("iv-drawer-close-button",F.Z);F.isInitialized=!0},AQe=function(F){F.Tj.push(g.b0("iv-teaser-shown",F.ED,F));
F.Tj.push(g.b0("iv-teaser-hidden",F.Xb_,F));F.Tj.push(g.b0("iv-teaser-clicked",F.Mx,F));F.Q2=!0},qQU=function(F,J){var b;
return J.onClickCommand&&((b=g.O(J.onClickCommand,g.CWe))==null?void 0:b.targetId)==="engagement-panel-error-corrections"?(F.eE=J,!0):!1},v_H=function(F,J){F.eE=J;
var b=F.G.getVideoData();if(!b)return!1;b=g.fC(b);if(b==null?0:b.markersMap)for(var I,u=0;((I=b)==null?void 0:I.markersMap.length)>u;u++){var w=void 0,M=(w=b)==null?void 0:w.markersMap[u];if(M.key==="ERROR_CORRECTION_MARKERS"&&(w=void 0,(M=(w=M.value)==null?void 0:w.markers)&&M.length>0))return I=void 0,J.startMs=((I=g.O(M[0],g.fNC))==null?void 0:I.timeRangeStartMillis)||0,F.eE=null,!0}return!1},F3=function(F,J){if(!qQU(F,J)||v_H(F,J)){var b=ait(F,J);
if(b){var I={aH:J,Ej:b.element,Sx:!1};if(J.onClickCommand)F.G.S("web_infocards_teaser_show_logging_fix")&&(F.Q2||AQe(F),uvt(F,J.id),b=F.findLastIndex(I),g.wy(F.cards,b,0,I));else{F.isInitialized||Mpb(F);uvt(F,J.id);var u=F.findLastIndex(I);g.wy(F.cards,u,0,I);b.Az(F.U,u);F.w2()}J.autoOpen?F.addCueRange(J.startMs,0x8000000000000,J.id,function(){F.T||(F.C=I,IC(F),esU(F,I),H_(F,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(b=F.context.G.getCurrentTime()*1E3,b<5E3&&b>J.startMs&&Kke(F,I),F.addCueRange(J.startMs,
J.startMs+1,J.id,function(){Kke(F,I)}),IC(F))}}},ait=function(F,J){switch(J.type){case "simple":F=F.Gj;
var b=J.displayDomain?{X:"div",K:"iv-card-image-text",sQ:J.displayDomain}:void 0;var I=n4z(J);b={X:"div",Dv:["iv-card"],j:[{X:"a",K:"iv-click-target",L:{href:J.url?oq(J.url)||"":""},j:[Uc(J.imageUrl,b),{X:"div",K:"iv-card-content",j:[c_("h2",void 0,J.title),I]}]}]};b=new g.U(b);xl(F,g.kM("iv-click-target",b.element),J,J.url);J=b;break;case "collaborator":F=F.Gj;b={X:"div",Dv:["iv-card","iv-card-channel"],j:[{X:"a",Dv:["iv-click-target"],L:{href:oq(J.url)||"","data-ytid":J.channelId},j:[Uc(J.profileImageUrl),
{X:"div",K:"iv-card-content",j:[UXk(J),{X:"h2",K:"iv-card-primary-link",sQ:J.title},xXb(J)]}]}]};b=new g.U(b);xl(F,g.kM("iv-click-target",b.element),J,J.url);J=b;break;case "playlist":F=F.Gj;b={X:"div",Dv:["iv-card","iv-card-playlist"],j:[{X:"a",K:"iv-click-target",L:{href:oq(J.url)||""},j:[Uc(J.Kf,{X:"div",K:"iv-card-image-overlay",j:[{X:"span",K:"iv-card-playlist-video-count",sQ:J.playlistVideoCount}]}),{X:"div",K:"iv-card-content",j:[UXk(J),c_("h2","iv-card-primary-link",J.title),xXb(J)]}]}]};
b=new g.U(b);xl(F,g.kM("iv-click-target",b.element),J,J.url);J=b;break;case "productListing":F=F.Gj;var u=J.offers.length!=0;b=["iv-card"];I="";var w=n4z(J);u&&(b.push("iv-card-product-listing"),I="iv-card-primary-link",w=J.offers[0],u=[],w.price&&u.push({X:"div",K:"iv-card-offer-price",sQ:w.price}),w.merchant&&u.push({X:"div",K:"iv-card-offer-merchant",sQ:w.merchant}),w={X:"div",j:u});u=J.url?oq(J.url)||"":"";b={X:"div",Dv:b,L:{tabindex:"0"},j:[{X:"a",Dv:["iv-card-image","iv-click-target"],L:{style:"background-image: url("+
J.imageUrl+");",href:u,"aria-hidden":"true",tabindex:"-1"}},{X:"div",K:"iv-card-content",j:[J.sponsored?{X:"div",K:"iv-card-sponsored",j:["Sponsorlu",{X:"div",K:"iv-ad-info-container",j:[{X:"div",K:"iv-ad-info",sQ:"{{adInfo}}"},{X:"div",K:"iv-ad-info-icon-container",j:[{X:"div",K:"iv-ad-info-icon"},{X:"div",K:"iv-ad-info-callout"}]}]}]}:"",{X:"a",K:"iv-click-target",L:{href:u},j:[c_("h2",I,J.title),w]}]}]};b=new g.U(b);I=g.H1("span");g.wK(I,"Videoyla ilgili oldu\u011funu d\u00fc\u015f\u00fcnd\u00fc\u011f\u00fcm\u00fcz i\u00e7in bu \u00fcr\u00fcn\u00fc g\u00f6r\u00fcyorsunuz. Google, sat\u0131c\u0131 taraf\u0131ndan tazmin edilebilir.");
b.Ce(I,"adInfo");xl(F,g.kM("iv-click-target",b.element),J,J.url);J=b;break;case "video":F=F.Gj;I=J.videoDuration?{X:"span",K:"iv-card-video-duration",sQ:J.videoDuration}:void 0;w=J.isLiveNow?{X:"span",Dv:["yt-badge","yt-badge-live"],sQ:"CANLI YAYINDA"}:null;u={X:"div",Dv:["iv-card","iv-card-video"],j:[{X:"a",K:"iv-click-target",L:{href:((b=J.url)==null?void 0:oq(b))||""},j:[Uc(J.Kf,I),{X:"div",K:"iv-card-content",j:[UXk(J),c_("h2","iv-card-primary-link",J.title),xXb(J),w]}]}]};b=new g.U(u);xl(F,g.kM("iv-click-target",
b.element),J,J.url);J=b;break;default:return null}return J},p9W=function(F){if(F.C)return F.C.aH.type==="productListing";
if(F.G.S("enable_wn_infocards")){var J;return!((J=F.cards)==null||!J.length)&&g.jw(F.cards,function(b){return b.aH.type==="productListing"})}return g.jw(F.cards,function(b){return b.aH.type==="productListing"})},IC=function(F){g.qr(F.G.getRootNode(),"ytp-cards-shopping-active",p9W(F))},Kke=function(F,J){if(!g.I3(F.G.getRootNode(),"ytp-cards-teaser-shown")){if(F.C!==J){var b=g.W8(),I=F.C?F.C.aH.r6:F.r6;
b&&I&&g.FX(b,[I]);F.C=J;IC(F)}(b=F.isInitialized&&F.Pb().style.display=="none")||(b=F.context.G.getPlayerState(),I=b===0&&F.context.G.getCurrentTime()===0,b=!(b===1||b===3||I));b||J.aH.teaserDurationMs&&F.G.ZZ(!0,{teaserText:J.aH.teaserText,durationMs:J.aH.teaserDurationMs,onClickCommand:J.aH.onClickCommand});F.nW.isActive()||((!F.T||!F.kQ.isActive()&&F.qf)&&esU(F,J),F.nW.start(910+J.aH.teaserDurationMs))}},esU=function(F,J){F.N.uT?(J=new S_([0,
F.U.scrollTop],[0,J.Ej.offsetTop],600,N4b),F.context.T.listen(J,"animate",function(b){F.U.scrollTop=b.y}),F.context.T.listen(J,"finish",function(b){F.U.scrollTop=b.y}),J.play()):(F.N.wY(!0),F.U.scrollTop=J.Ej.offsetTop,F.N.wY(!1))},uN=function(F){return F.C&&F.C.aH?F.C.aH:F.cards[0]&&F.cards[0].aH?F.cards[0].aH:null},IiV=function(F,J){return g.xL(F.cards,function(b){return b.aH.id===J})},wp=function(F,J,b){nt.call(this,F,J);
this.annotation=b;this.isActive=!1},g_b=function(F){var J=F.annotation.data;
"start_ms"in J&&"end_ms"in J&&F.addCueRange(Number(J.start_ms),Number(J.end_ms),F.annotation.id,function(){F.show()},function(){F.hide()})},MT=function(F,J,b){wp.call(this,F,J,b);
this.U=null;this.V=!1;this.T=null;this.Z=!1;this.C=this.W=this.D=null},m9W=function(F,J){var b=b===void 0?0:b;
var I=awR(J).width;g.yf(J,I);b=new iGU(J,[I,J.offsetTop],[I-I-b,J.offsetTop],200,zl5);g.k(F,b);F.context.T.listen(b,"begin",function(){g.Wc(J,!0)});
b.play()},zsH=function(F,J){if(J.channel_name){var b=F.createElement({X:"div",
Dv:["iv-branding-context-name"],sQ:J.channel_name}),I=F.createElement({X:"div",Dv:["iv-branding-context-subscribe"]}),u=J.standalone_subscribe_button_data;u&&(F.C=new g.Aq(u.subscribeText,u.subscribeCount,u.unsubscribeText,u.unsubscribeCount,!!u.enabled,!!u.classic,J.channel_id,!!u.subscribed,u.feature,J.session_data.itct,F.context.G,!1),F.C.Az(I));var w=F.createElement({X:"div",Dv:["iv-branding-context-subscribe-caret"]}),M=F.createElement({X:"div",Dv:["branding-context-container-inner"]});M.appendChild(w);
M.appendChild(b);M.appendChild(I);g.Wc(M,!1);var q=F.createElement({X:"div",Dv:["branding-context-container-outer"]});q.appendChild(M);g.aN(q,"right",J.image_width+"px");g.F9(F.Pb(),q);F.T=new g.ty(function(){yQH(F,M,q)},500);
g.k(F,F.T);F.context.C.listen(F.Pb(),"mouseover",function(){i5b(F,M,q,w,J.image_height)});
F.context.C.listen(F.Pb(),"mouseout",function(){F.T.start()})}},i5b=function(F,J,b,I,u){F.T.stop();
if(!F.Z){var w=g.fL(J);F.C||(J.style.width=g.m2(w.width,!0),b.style.width=g.m2(w.width,!0));g.aN(I,"top",w.height-Math.max(Math.min(w.height,u)/2+10,20)+"px");g.aN(I,"right","1px");F.Z=!0;g.Wc(J,!0);F.D=new g.ty(function(){g.uG(this.Pb(),"iv-branding-active")},0,F);
F.D.start()}},yQH=function(F,J,b){g.Mr(F.Pb(),"iv-branding-active");
F.W=new g.ty(function(){g.Wc(J,!1);F.C||(b.style.width=g.m2(0,!0))},250);
F.W.start();F.Z=!1},N3b=function(F,J,b,I,u,w,M){this.C=F;
this.T=J;this.rD=b;this.videoData=I;this.logger=u;this.G=w;this.U=M},lik=function(F,J,b){wp.call(this,F,J,b);
var I=this;this.Y=this.isCollapsed=this.N=!1;this.W=5E3;this.U=this.T=this.C=this.Z=null;this.V=this.createElement({X:"div",Dv:["iv-promo-contents"]});this.D=new g.ty(function(){I.C.setAttribute("aria-hidden","true");g.Wc(I.T,!1);g.Wc(I.U,!0)},700,this);
g.k(this,this.D)},Wkz=function(F){var J=F.annotation.data;
if(F.annotation.style==="cta")var b=6;else if(F.annotation.style==="video"||F.annotation.style==="playlist")b=7;F.W=J.collapsedelay_ms||F.W;var I=["iv-promo","iv-promo-inactive"];F.Pb().setAttribute("aria-hidden","true");F.Pb().setAttribute("aria-label","Tan\u0131t\u0131m");F.Pb().tabIndex=0;var u=F.annotation.tF(),w=J.image_url;if(w){var M=F.createElement({X:"div",Dv:["iv-promo-img","iv-click-target"]});w=F.createElement({X:"img",L:{src:w,"aria-hidden":"true"}});M.appendChild(w);J.video_duration&&
!J.is_live?(w=F.createElement({X:"span",K:"iv-promo-video-duration",sQ:J.video_duration}),M.appendChild(w)):J.playlist_length&&(w=F.createElement({X:"span",K:"iv-promo-playlist-length",sQ:J.playlist_length.toString()}),M.appendChild(w));u&&t0(F,M,u,F.annotation.id,J.session_data,void 0,b)}u?(w=F.createElement({X:"a",K:"iv-promo-txt"}),g.Sp(w,oq(u)),F.C=w):F.C=F.createElement({X:"div",K:"iv-promo-txt"});switch(F.annotation.style){case "cta":case "website":var q=F.createElement({X:"p",j:[{X:"strong",
sQ:J.text_line_1}]});var v=F.createElement({X:"p",j:[{X:"span",K:"iv-promo-link",sQ:J.text_line_2}]});if(w=J.text_line_3){I.push("iv-promo-website-card-cta-redesign");var a=F.createElement({X:"button",Dv:["iv-promo-round-expand-icon","ytp-button"]});w=F.createElement({X:"button",Dv:["iv-button","iv-promo-button"],j:[{X:"span",K:"iv-button-content",sQ:w}]});var e=F.createElement({X:"div",K:"iv-promo-button-container"});e.appendChild(w);u&&t0(F,F.Pb(),u,F.annotation.id,J.session_data,void 0,b)}g.uG(F.C,
"iv-click-target");u&&t0(F,F.C,u,F.annotation.id,J.session_data,void 0,b);break;case "playlist":case "video":q=F.createElement({X:"p",j:[{X:"span",sQ:J.text_line_1}]}),v=F.createElement({X:"p",j:[{X:"strong",sQ:J.text_line_2}]}),J.is_live&&(q=v,v=F.createElement({X:"span",Dv:["yt-badge","iv-promo-badge-live"],sQ:"CANLI YAYINDA"})),g.uG(F.C,"iv-click-target"),u&&t0(F,F.C,u,F.annotation.id,J.session_data,void 0,b),I.push("iv-promo-video")}q&&F.C.appendChild(q);v&&F.C.appendChild(v);F.V.appendChild(F.C);
e&&F.V.appendChild(e);b=F.createElement({X:"div",K:"iv-promo-actions"});F.U=F.createElement({X:"button",Dv:["iv-promo-expand","ytp-button"]});F.U.title="Geni\u015flet";F.context.C.listen(F.U,"click",function(K){fiW(F,5E3,K)});
b.appendChild(F.U);g.Wc(F.U,!1);F.context.C.listen(F.Pb(),"mouseover",F.TDv,F);F.context.C.listen(F.Pb(),"mouseout",F.UfN,F);F.context.C.listen(F.Pb(),"touchend",function(K){fiW(F,5E3,K)});
F.T=F.createElement({X:"button",Dv:["iv-promo-close","ytp-button"]});F.T.title="Kapat";F.context.C.listen(F.T,"click",F.annotation.style==="cta"&&J.text_line_3?F.IY:F.NA,F);b.appendChild(F.T);g.wD(F.Pb(),I);M&&(g.F9(F.Pb(),M),a&&M.appendChild(a));g.F9(F.Pb(),F.V);g.F9(F.Pb(),b)},fiW=function(F,J,b){b.stopPropagation();
d9z(F);E_m(F,J);F.C.focus()},j0W=function(F){F.isCollapsed||F.Y||F.Z||(g.uG(F.Pb(),"iv-promo-collapsed"),F.isCollapsed=!0,F.D.start())},d9z=function(F){F.D.stop();
F.isCollapsed&&(g.An(F.Pb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),F.isCollapsed=!1,F.C&&F.C.removeAttribute("aria-hidden"),g.Wc(F.U,!1),g.Wc(F.T,!0))},E_m=function(F,J){F.Z||(F.Z=g.Wj(function(){Gyz(this);
j0W(this)},J,F))},Gyz=function(F){F.Z&&(g.Qz.clearTimeout(F.Z),F.Z=null)},Vpb=function(F){this.G=F},w9U=function(F,J,b){J&&(b?AK(F,J.map(function(I){return g.TM(I,b)})):AK(F,J))},AK=function(F,J,b,I){var u=1,w=void 0,M=-1;
if(b){var q=!1;w=function(){u--;u||q||(clearTimeout(M),q=!0,b())};
M=setTimeout(function(){q=!0;b()},1E3)}J=g.N(J||[]);
for(var v=J.next();!v.done;v=J.next())v=v.value,u++,g.Xp(v,w);I&&(u++,I!==0&&F.G.sendVideoStatsEngageEvent(I,w))},PwW=function(F){g.GN.call(this,F);
var J=this;this.Tj=this.Y=!1;this.loadNumber=0;this.W={};this.logger=new Vpb(this.player);this.Z=new g.s5(this);this.D=this.V=null;this.events=new g.s5(this);this.EV=this.N=this.C=null;this.eE=[];g.k(this,this.Z);this.Z.B(this.player,"onVideoAreaChange",function(){J.publish("onVideoAreaChange")});
this.Z.B(this.player,"onHideControls",function(){J.publish("onHideControls")});
this.Z.B(this.player,"onShowControls",function(){J.publish("onShowControls")});
this.Z.B(this.player,"resize",function(I){J.publish("resize",I)});
this.Z.B(this.player,"presentingplayerstatechange",function(I){J.publish("presentingplayerstatechange",I)});
this.subscribe("presentingplayerstatechange",this.lG,this);this.subscribe("resize",this.TN,this);this.player.J().fW.subscribe("vast_info_card_add",this.YP,this);g.k(this,this.events);this.Gj=this.createElement({X:"div",K:"video-custom-annotations"});this.U=new g.U({X:"div",Dv:["ytp-player-content","ytp-iv-player-content"]});g.k(this,this.U);g.Pp(this.player,this.U.element,4);this.U.hide();this.T=new g.U({X:"div",Dv:["ytp-iv-video-content"]});g.k(this,this.T);F=this.createElement({X:"div",K:"video-annotations"});
F.appendChild(this.Gj);this.T.element.appendChild(F);this.X$()&&this.load();var b=this.createElement({X:"style"});(g.D8("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.ID(b)});
if(F=b.sheet)F.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),F.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),F.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),F.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),F.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),F.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),F.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),F.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),F.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),F.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},B3W=function(F){F=F.createElement({X:"div",
Dv:["annotation","annotation-type-custom"]});g.Wc(F,!1);return F},T3b=function(F,J){J=!J.isCued()&&!g.x(J,1024);
F.U.wY(J);F.T.wY(J)},rQm=function(F,J,b){F.Y=!0;
F.D=g.E6(J,b)},SQt=function(F,J){for(var b={},I=g.N(J.attributes),u=I.next();!u.done;u=I.next())u=u.value,b[u.name]=u.nodeValue;
for(I=0;I<J.childNodes.length;I++)if(u=J.childNodes[I],g.Um(u)&&u.nodeType==1){if(b[u.tagName])var w=b[u.tagName];else if(u.tagName==="data"){u.childNodes.length>0&&(w=u.childNodes[0].nodeValue,b[u.tagName]=typeof w==="string"?w.trim():w);continue}else w=[],b[u.tagName]=w;u&&u.tagName==="TEXT"?u.childNodes.length===1&&u.childNodes[0].nodeType===3?w.push(u.childNodes[0].nodeValue):w.push(""):u&&w.push(SQt(F,u))}return b},Cwm=function(F){var J=F.player.getVideoData();
if(J.Jz){var b=F.player.J().fW.get(J.videoId);if(b){var I={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(u,w,M){u=F.loadNumber;w=J.videoId;F.loaded&&F.loadNumber===u&&F.player.getVideoData().videoId===w&&(M=g.Kl(M)&&M.responseXML?M.responseXML:null)&&s05(F,M)}};
g.Lw()&&(I.onFinish=YQU(F,I.onFinish));I.postParams={ic_only:"1"};$9U(I,b);F.Y=!0;g.E6(J.Jz,I)}}},$9U=function(F,J){F.method="POST";
F.postParams=F.postParams||{};J.Xj&&(F.postParams.ic_coll=J.Xj);J.d4&&(F.postParams.ic_xml=J.d4);J.xE&&(F.postParams.ic_track=J.xE)},X9m=function(F){var J=new g.U({X:"div"});
g.Wc(J.element,!1);var b=new FkU(F.player,J.element,qT(F));g.k(b,J);J.Az(F.U.element);b.uo();return b},RsW=function(F,J){var b,I;
if(J=(b=J.getWatchNextResponse())==null?void 0:(I=b.cards)==null?void 0:I.cardCollectionRenderer)F.Tj=!0,Q0R(F,J),J.headerText&&F.EV&&(b=g.Kr(J.headerText),F.EV.setAttribute("title",b))},qT=function(F){if(!F.N){var J=new lwk(F);
g.k(F,J);var b=new g.dR(F);g.k(F,b);F.N=new N3b(J,b,F.player.J(),F.player.getVideoData(),F.logger,F.player,F.jm)}return F.N},s05=function(F,J){var b=!1,I=J.getElementsByTagName("annotations");
if(I&&!(I.length<1)&&(I=I[0].getAttribute("itct"))){var u=g.W8();if(u){var w=g.fO();w&&g.tE(g.OT)(void 0,u,w,[g.NY(I)])}}J=J.getElementsByTagName("annotation");for(I=0;I<J.length;I++){w=SQt(F,J[I]);u=null;try{if(w){var M=w.id,q=/.+/;var v=typeof M==="string"&&q!=null&&M!=null&&M.match(q)?M:"";var a=Oc(w.type,D91),e=Oc(w.style,kym),K=CP1(w.data),p=K.length!==0?JSON.parse(K):{};var m=w.action;w=OGW;if(m==null)var y=null;else if(g.ca(m)){q=[];for(var f=g.N(m),d=f.next();!d.done;d=f.next()){var G=w(d.value);
G&&q.push(G)}y=q}else{var P=w(m);y=P?[P]:[]}u=v&&a?new o4R(v,a,e,y,p):null}else u=null}catch(uk){}if(u)if(u.type==="branding"||u.type==="promotion"){w=F;q=u;var r=B3W(w),Q=null;switch(q.type){case "branding":if(w.player.J().Ly)break;w.U.element.appendChild(r);Q=new MT(r,qT(w),q);break;case "promotion":g.Pp(w.player,r,4),Q=new lik(r,qT(w),q)}Q&&Q.uo();if(w=Q)g.k(F,w),F.W[u.id]=w}else if(u.type==="card"||u.type==="drawer"){F.C||(F.C=X9m(F),g.k(F,F.C));if(u.type==="card"){r=F.C;var D=(b=u)&&b.data&&
b.data.card_type;u=b.data;if(D)switch(w=u.tracking||{},w={Hr:w.impression,click:w.click,close:w.close,tL:w.teaser_impression,HM:w.teaser_click},q=u.tracking_params||{},Q=null,D){case "collaborator":b={id:b.id,timestamp:u.timestamp||0,type:u.card_type,teaserText:u.teaser_text,teaserDurationMs:u.teaser_duration_ms,startMs:u.start_ms,autoOpen:u.auto_open||!1,sessionData:u.session_data||{},sponsored:u.sponsored||!1,dg:w,X2:q.card?g.NY(q.card):null,Z2:q.teaser?g.NY(q.teaser):null,r6:q.icon?g.NY(q.icon):
null,channelId:u.channel_id,customMessage:u.custom_message?u.custom_message:null,profileImageUrl:u.image_url,title:u.title,metaInfo:u.meta_info,url:h0({pause_on_navigation:u.pause_on_navigation,target:u.target||"new",value:u.url}),onClickCommand:null};F3(r,b);break;case "playlist":b={id:b.id,timestamp:u.timestamp||0,type:u.card_type,teaserText:u.teaser_text,teaserDurationMs:u.teaser_duration_ms,startMs:u.start_ms,autoOpen:u.auto_open||!1,sessionData:u.session_data||{},sponsored:u.sponsored||!1,dg:w,
X2:q.card?g.NY(q.card):null,Z2:q.teaser?g.NY(q.teaser):null,r6:q.icon?g.NY(q.icon):null,Kf:u.image_url,playlistVideoCount:u.playlist_video_count,customMessage:u.custom_message?u.custom_message:null,title:u.title,metaInfo:u.meta_info,url:h0({pause_on_navigation:u.pause_on_navigation,target:u.target||"new",value:u.url}),onClickCommand:null};F3(r,b);break;case "productListing":u.signin_url&&(Q=h0({target:"current",value:u.signin_url}));D=[];for(var t=u.offers||[],n=0;n<t.length;n++)D.push(new tDt(g.Zi(t[n].merchant),
g.Zi(t[n].price)));b={id:b.id,timestamp:u.timestamp||0,type:u.card_type,teaserText:u.teaser_text,teaserDurationMs:u.teaser_duration_ms,startMs:u.start_ms,autoOpen:u.auto_open||!1,sessionData:u.session_data||{},sponsored:u.sponsored||!1,dg:w,X2:q.card?g.NY(q.card):null,Z2:q.teaser?g.NY(q.teaser):null,r6:q.icon?g.NY(q.icon):null,imageUrl:u.image_url,displayDomain:u.display_domain?u.display_domain:null,showLinkIcon:!!u.show_link_icon,QP:u.button_icon_url?u.button_icon_url:null,title:u.title,customMessage:u.custom_message?
u.custom_message:null,url:h0({pause_on_navigation:u.pause_on_navigation,target:u.target||"new",value:u.url}),f$D:Q,iPG:u.signin_title?u.signin_title:void 0,DiR:u.signin_message?u.signin_message:void 0,offers:D,onClickCommand:null};F3(r,b);break;case "simple":b={id:b.id,timestamp:u.timestamp||0,type:u.card_type,teaserText:u.teaser_text,teaserDurationMs:u.teaser_duration_ms,startMs:u.start_ms,autoOpen:u.auto_open||!1,sessionData:u.session_data||{},sponsored:u.sponsored||!1,dg:w,X2:q.card?g.NY(q.card):
null,Z2:q.teaser?g.NY(q.teaser):null,r6:q.icon?g.NY(q.icon):null,imageUrl:u.image_url,displayDomain:u.display_domain?u.display_domain:null,showLinkIcon:!!u.show_link_icon,QP:u.button_icon_url?u.button_icon_url:null,title:u.title,customMessage:u.custom_message?u.custom_message:null,url:h0({pause_on_navigation:u.pause_on_navigation,target:u.target||"new",value:u.url}),onClickCommand:null};F3(r,b);break;case "video":b={id:b.id,timestamp:u.timestamp||0,type:u.card_type,teaserText:u.teaser_text,teaserDurationMs:u.teaser_duration_ms,
startMs:u.start_ms,autoOpen:u.auto_open||!1,sessionData:u.session_data||{},sponsored:u.sponsored||!1,dg:w,X2:q.card?g.NY(q.card):null,Z2:q.teaser?g.NY(q.teaser):null,r6:q.icon?g.NY(q.icon):null,Kf:u.image_url,videoDuration:u.video_duration||null,customMessage:u.custom_message?u.custom_message:null,title:u.title,metaInfo:u.meta_info,isLiveNow:!!u.is_live_now,url:h0({pause_on_navigation:u.pause_on_navigation,target:u.target||"new",value:u.url}),onClickCommand:null},F3(r,b)}}else JQH(F.C,u);b=!0}}b&&
(VW(F.player),F.TN())},Q0R=function(F,J){var b=!1;
F.C||(F.C=X9m(F),g.k(F,F.C));for(var I=g.N(J.cards||[]),u=I.next();!u.done;u=I.next())u=u.value,u.cardRenderer&&(b5z(F.C,u.cardRenderer),b=!0);if(b){var w;(w=F.player.getVideoData())!=null&&g.PE(w)||(b=F.C,I=J.headerText?g.Kr(J.headerText):"",g.wK(b.Um,I),b.Y&&b.Y.setAttribute("title",I),b.context.videoData.eventId&&(b.eventId=b.context.videoData.eventId),b.WN=J.trackingParams?g.NY(J.trackingParams):null,b.V=J.closeButton.infoCardIconRenderer.trackingParams?g.NY(J.closeButton.infoCardIconRenderer.trackingParams):
null,b.r6=J.icon.infoCardIconRenderer.trackingParams?g.NY(J.icon.infoCardIconRenderer.trackingParams):null,F.TN());VW(F.player)}},O5z=function(F,J,b,I,u){if(!F.player.J().Ly){var w=[];
J.navigationEndpoint&&g.O(J.navigationEndpoint,g.fY)&&g.O(J.navigationEndpoint,g.fY).browseId&&w.push(new Rle("openUrl","click",new XoV("/channel/"+g.O(J.navigationEndpoint,g.fY).browseId,"new",!0,!0)));var M=J.watermark.thumbnails[0];I={channel_name:J.channelName,end_ms:J.endTimeMs,image_height:M.height,image_type:1,image_url:M.url,image_width:M.width,is_mobile:!1,session_data:{annotation_id:b,ei:u,feature:"iv",itct:J.trackingParams,src_vid:I},start_ms:J.startTimeMs};if(J.subscribeButton&&g.O(J.subscribeButton,
g.WE)){I.channel_id=g.O(J.subscribeButton,g.WE).channelId;var q;J=g.O(J.subscribeButton,g.WE);M=u=null;J.subscribed?(J.subscriberCountWithUnsubscribeText&&(u=g.Kr(J.subscriberCountWithUnsubscribeText)),J.subscriberCountText&&(M=g.Kr(J.subscriberCountText))):(J.subscriberCountText&&(u=g.Kr(J.subscriberCountText)),J.subscriberCountWithSubscribeText&&(M=g.Kr(J.subscriberCountWithSubscribeText)));var v,a=((v=g.O((q=J.signInEndpoint)==null?void 0:q.commandMetadata,g.Nm))==null?void 0:v.url)||"";q={subscribeText:g.Kr(J.unsubscribedButtonText),
subscribeCount:u||"",unsubscribeText:g.Kr(J.subscribedButtonText),unsubscribeCount:M||"",enabled:J.enabled||!1,classic:!1,subscribed:J.subscribed||!1,feature:"iv",signInUrl:a};I.standalone_subscribe_button_data=q}w=new o4R(b,"branding","branding",w,I);q=B3W(F);F.U.element.appendChild(q);w=new MT(q,qT(F),w);w.uo();g.k(w,w);F.W[b]=w}},YQU=function(F,J){return function(){var b=g.Ba.apply(0,arguments);
F.iR()||F.eE.push(g.D_.Ti(function(){J.apply(null,g.W(b))}))}},o_b=function(F){return F==="annotation-editor"||F==="live-dashboard"};
g.ly.prototype.ZZ=g.IG(40,function(F,J){var b=g.Dg(this.TF());b&&b.ZZ(F,J)});
var B_={},Tz=null;g.Fb(S_,g.vV);g.A=S_.prototype;g.A.getDuration=function(){return this.duration};
g.A.play=function(F){if(F||this.C==0)this.progress=0,this.coords=this.U;else if(this.isPlaying())return!1;rH(this);this.startTime=F=g.L3();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.Z=this.startTime;this.progress||this.pJ();this.Jr("play");this.isPaused()&&this.Jr("resume");this.C=1;var J=g.n3(this);J in B_||(B_[J]=this);po8();g4U(this,F);return!0};
g.A.stop=function(F){rH(this);this.C=0;F&&(this.progress=1);mXV(this,this.progress);this.onStop();this.ly()};
g.A.pause=function(){this.isPlaying()&&(rH(this),this.C=-1,this.Jr("pause"))};
g.A.X_=function(){this.C==0||this.stop(!1);this.Jr("destroy");S_.k7.X_.call(this)};
g.A.destroy=function(){this.dispose()};
g.A.Xv=function(){this.Jr("animate")};
g.A.Jr=function(F){this.dispatchEvent(new yxb(F,this))};
g.Fb(yxb,g.SX);g.Fb(sc,S_);sc.prototype.T=function(){};
sc.prototype.Xv=function(){this.T();sc.k7.Xv.call(this)};
sc.prototype.ly=function(){this.T();sc.k7.ly.call(this)};
sc.prototype.pJ=function(){this.T();sc.k7.pJ.call(this)};
g.Fb(iGU,sc);iGU.prototype.T=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.z(lwk,g.R);g.A=lwk.prototype;g.A.listen=function(F,J,b,I){b=(0,g.tJ)(b,I||this.U);F=g.l8(F,J,b);this.C.push(F);return F};
g.A.Sk=function(F,J,b,I){b=(0,g.tJ)(b,I||this.U);F=elU(F,J,b);this.C.push(F);return F};
g.A.iX=function(F){g.fw(F);g.Hk(this.C,F)};
g.A.removeAll=function(){g.fw(this.C);this.C.length=0};
g.A.X_=function(){this.removeAll();g.R.prototype.X_.call(this)};g.z(dXt,g.GN);g.A=dXt.prototype;g.A.load=function(){g.GN.prototype.load.call(this);if(!Ct(this)){var F=g.bm7(this.player.getVideoData());F?(F=WCH(F,E4V(this)),X2(this,F,!1)):jMb(this)}};
g.A.unload=function(){X2(this,null);this.Z&&(this.Z.abort(),this.Z=null);g.GN.prototype.unload.call(this)};
g.A.qJ=function(F,J){return Ct(this)?F==="loadCustomEndscreenRenderer"?(F=WCH(J,"new"),X2(this,F),!0):null:null};
g.A.getOptions=function(){return Ct(this)?["loadCustomEndscreenRenderer"]:[]};
g.A.mO=function(){if(this.endscreen&&this.endscreen.elements){var F=this.player.getVideoContentRect();if(F&&F.width!==0&&F.height!==0){var J=this.player.getPlayerSize();if(J&&J.width!==0&&J.height!==0){var b=F.width/F.height;var I=0;for(var u=-1,w=0;w<hs1.length;w++){var M=Math.abs(J.width-hs1[w]);if(u===-1||I>=M)u=w,I=M}I=cQb[u];this.T&&g.aN(this.T.element,"outline-width",Math.max(J.width,J.height)+"px");for(J=0;J<this.endscreen.elements.length;++J)if(w=this.endscreen.elements[J].id,u=this.U[w],
M=this.W[w],u&&M){var q=M.width*b/M.aspectRatio,v=Math.round(M.width*F.width);w=Math.round(q*F.height);var a=F.left+Math.round(M.left*F.width),e=F.top+Math.round(M.top*F.height);g.lu(u.element,v,w);g.yf(u.element,a,e);g.An(u.element,U9R);v>256||w>256?g.uG(u.element,"ytp-ce-large-round"):v>96||w>96?g.uG(u.element,"ytp-ce-medium-round"):g.uG(u.element,"ytp-ce-small-round");g.An(u.element,x9U);v=M.left+M.width/2;M=M.top+q/2;g.uG(u.element,v<=.5&&M<=.5?"ytp-ce-top-left-quad":v>.5&&M<=.5?"ytp-ce-top-right-quad":
v<=.5&&M>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.An(u.element,cQb);g.uG(u.element,I);(u=g.Oa(document,"div","ytp-ce-expanding-overlay-body",u.element)[0])&&g.aN(u,"height",w+"px")}}}}};
g.A.onCueRangeEnter=function(F){if(this.endscreen)if(F.getId()==="ytp-ce-in-endscreen")kl(this,this.endscreen.impressionUrls),(F=g.W8())&&this.endscreen.visualElement&&g.H8(F,this.endscreen.visualElement),this.C&&(g.uG(this.C,"ytp-ce-element-show"),this.C.removeAttribute("aria-hidden"),this.player.AD()?g.uG(this.C,"ytp-ce-hide-button-lower"):g.Mr(this.C,"ytp-ce-hide-button-lower"));else{F=F.getId().substring(15);var J=this.U[F],b=this.W[F];g.uG(J.element,"ytp-ce-element-show");J.element.removeAttribute("aria-hidden");
J=this.player.getRootNode();g.uG(J,"ytp-ce-shown");kl(this,b.impressionUrls);(J=g.W8())&&g.H8(J,b.visualElement);this.player.J().V&&this.player.jE("endscreenelementshown",F)}};
g.A.onCueRangeExit=function(F){if(F.getId()==="ytp-ce-in-endscreen")this.C&&(g.Mr(this.C,"ytp-ce-element-show"),this.C.setAttribute("aria-hidden","true"));else{F=F.getId().substring(15);var J=this.U[F];g.Mr(J.element,"ytp-ce-element-show");J.element.setAttribute("aria-hidden","true");J=this.player.getRootNode();g.Mr(J,"ytp-ce-shown");this.player.J().V&&this.player.jE("endscreenelementhidden",F)}};
g.A.AeW=function(F){var J=this;F.target===window&&(new g.ty(function(){for(var b=g.N(Object.values(J.U)),I=b.next();!I.done;I=b.next())g.An(I.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.A.wY=function(F){for(var J=g.N(Object.values(this.U)),b=J.next();!b.done;b=J.next())b=b.value,F?b.element.setAttribute("hidden",""):b.element.removeAttribute("hidden")};
g.A.o7_=function(F){this.C&&this.player.getRootNode().removeChild(this.C);F&&(g.uG(F,"ytp-ce-hide-button-container"),this.C=F,g.Pp(this.player,this.C,4))};
var hs1=[346,426,470,506,570,640,853,1280,1920],cQb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),x9U=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],U9R=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var QMm={JNR:"current",Ocj:"new"};var DXL={CLOSE:"close",MS_:"openUrl",SUBSCRIBE:"subscribe"},kbz={fj_:"click",CLOSE:"close",yDW:"hidden",uiG:"rollOut",GQj:"rollOver",fcW:"shown"};o4R.prototype.tF=function(){var F=hle(this,function(J){return J.type==="openUrl"&&J.url!=null});
return F?F.url:null};
var kym={KPQ:"anchored",Lm:"branding",CHANNEL:"channel",o__:"cta",j5f:"highlightText",zTG:"label",PLAYLIST:"playlist",POPUP:"popup",VpI:"speech",SUBSCRIBE:"subscribe",yr_:"title",VIDEO:"video",Mn_:"website"},D91={Lm:"branding",uYR:"card",Ijz:"drawer",Y2G:"highlight",c4E:"marker",nKf:"promotion",TEXT:"text",rO_:"widget"};g.z(nt,g.R);g.A=nt.prototype;g.A.addCueRange=function(F,J,b,I,u){F=new g.b6(F,J,{id:b,namespace:"annotations_module"});I&&this.KW.set(F,I);u&&this.Jz.set(F,u);this.context.G.TU([F],1)};
g.A.uo=function(){this.context.U.subscribe("resize",this.w2,this)};
g.A.Pb=function(){return this.element};
g.A.sE=function(F,J,b,I,u,w){if(this.bR)return!1;w&&(w.stopPropagation(),w.preventDefault());this.navigate(F,b,I,u);return!1};
g.A.show=function(){};
g.A.hide=function(){};
g.A.destroy=function(){g.ID(this.Pb())};
g.A.w2=function(){};
g.A.navigate=function(F,J,b,I){var u=this,w=oq(F);if(w){var M=HGz(w,F.target),q=function(){F.C&&u.context.G.pauseVideo();var v=u.context.videoData.T0||!1,a=g.bi(w||"");v&&a&&(a.v||a.list)?u.context.G.yp(a.v,J,a.list,!1):g.RJ(w||"",M==="current"?"_top":void 0,J)};
M==="new"&&(q(),q=null);AK(this.context.logger,b,q,I);ZGk(w)||(b=g.W8(),I=J.itct,b&&I&&g.Jr(b,g.NY(I)))}};
g.A.X_=function(){this.KW.clear();this.Jz.clear();g.R.prototype.X_.call(this)};
g.A.createElement=function(F){F=new g.U(F);g.k(this,F);return F.element};g.z(FkU,nt);g.A=FkU.prototype;g.A.xR=function(){this.eE&&F3(this,this.eE)};
g.A.isAvailable=function(){var F;if(F=!!this.cards.length)(F=this.G.getRootNode())?(F=g.fL(F),F=173<F.width&&173<F.height):F=!1;return F};
g.A.w2=function(){var F=this.isAvailable();g.Wc(this.Pb(),F);g.qr(this.context.G.getRootNode(),g.QA.IV_DRAWER_ENABLED,F);VW(this.G)};
g.A.destroy=function(){this.G.ZZ(!1);try{this.G.getRootNode().removeChild(this.Z)}catch(F){}g.Iu(this.Tj);g.Ve(this.dD);this.zj&&this.zj.dispose();this.D&&this.D.dispose();nt.prototype.destroy.call(this)};
g.A.tj=function(){var F=this;this.context.C.listen(g.c1("iv-drawer-close-button",this.Z),"click",this.jw,this);this.context.C.listen(this.U,"touchend",function(){F.kQ.start()});
this.context.C.listen(this.U,"scroll",this.Di,this);this.context.U.subscribe("onHideControls",function(){F.qf=!0});
this.context.U.subscribe("onShowControls",function(){F.qf=!1});
this.context.U.subscribe("onVideoAreaChange",function(){F.qf=g.I3(F.G.getRootNode(),"ytp-autohide")});
this.Tj.push(g.b0("iv-button-shown",this.Zkj,this));this.Tj.push(g.b0("iv-button-hidden",this.e8Q,this));AQe(this)};
g.A.findLastIndex=function(F){if(this.cards.length===0)return 0;var J=g.nz(this.cards,function(b){return F.aH.startMs>b.aH.startMs||F.aH.startMs===b.aH.startMs&&F.aH.timestamp>=b.aH.timestamp?!0:!1});
return J===-1?0:J+1};
g.A.jw=function(){if(this.T){AK(this.context.logger,uN(this).dg.close);var F=g.W8();F&&this.V&&g.Jr(F,this.V);Lt(this)}};
g.A.Di=function(){g.qr(this.Z,"iv-drawer-scrolled",this.U.scrollTop>0)};
g.A.Zkj=function(){var F=g.W8(),J=uN(this);J=J?J.r6:this.r6;F&&J&&g.LO(F,[J])};
g.A.e8Q=function(){var F=g.W8(),J=uN(this);J=J?J.r6:this.r6;F&&J&&g.FX(F,[J])};
g.A.ED=function(){var F=uN(this);AK(this.context.logger,F.dg.tL);var J=g.W8();if(J&&F)if(this.G.S("web_infocards_teaser_show_logging_fix")){var b=[];F.Z2&&b.push(F.Z2);F.r6&&b.push(F.r6);b.length>0&&g.LO(J,b)}else g.LO(J,[F.Z2,F.r6])};
g.A.Xb_=function(){var F=g.W8(),J=uN(this);F&&J&&g.FX(F,[J.Z2])};
g.A.Mx=function(F){var J=uN(this),b=g.W8();this.C?F?(F=this.context.logger,AK(F,J.dg.HM),F.G.sendVideoStatsEngageEvent(4,void 0),b&&J.Z2&&g.Jr(b,J.Z2)):(F=this.context.logger,AK(F,J.dg.HM),F.G.sendVideoStatsEngageEvent(4,void 0),b&&J.r6&&g.Jr(b,J.r6)):(F=this.context.logger,AK(F,J.dg.HM),F.G.sendVideoStatsEngageEvent(4,void 0),b&&this.r6&&g.Jr(b,this.r6))};g.z(wp,nt);wp.prototype.uo=function(){nt.prototype.uo.call(this);g_b(this)};
wp.prototype.show=function(){nt.prototype.show.call(this);var F=g.W8(),J=this.annotation.data;F&&J&&(J=J.session_data)&&g.LO(F,[g.NY(J.itct)])};
wp.prototype.hide=function(){nt.prototype.hide.call(this);var F=g.W8(),J=this.annotation.data;F&&J&&(J=J.session_data)&&g.FX(F,[g.NY(J.itct)])};g.z(MT,wp);
MT.prototype.show=function(){if(!this.isActive){wp.prototype.show.call(this);if(!this.V){g.uG(this.Pb(),"iv-branding");var F=this.annotation.data;this.U=this.createElement({X:"img",Dv:["branding-img","iv-click-target"],L:{"aria-label":"Kanal filigran\u0131",src:F.image_url,width:F.image_width,height:F.image_height}});g.Wc(this.U,!1);var J=this.createElement({X:"button",Dv:["branding-img-container","ytp-button"]});J.appendChild(this.U);this.Pb().appendChild(J);var b=this.annotation.tF();b&&t0(this,
J,b,this.annotation.id,F.session_data);this.context.G.S("disable_branding_context")||zsH(this,F);this.V=!0}g.Wc(this.Pb(),!0);this.isActive=!0;if(this.U){try{m9W(this,this.U)}catch(I){}g.uG(this.context.G.getRootNode(),"ytp-branding-shown");this.context.G.getRootNode().style.setProperty("--branding-image-width",this.U.getAttribute("width")+"px")}}};
MT.prototype.hide=function(){this.isActive&&(wp.prototype.hide.call(this),g.Wc(this.Pb(),!1),this.isActive=!1,g.Mr(this.context.G.getRootNode(),"ytp-branding-shown"))};
MT.prototype.destroy=function(){this.C&&(this.C.dispose(),this.C=null);g.Mr(this.context.G.getRootNode(),"ytp-branding-shown");wp.prototype.destroy.call(this)};g.z(lik,wp);g.A=lik.prototype;g.A.show=function(){this.isActive||(wp.prototype.show.call(this),this.N||(Wkz(this),this.N=!0),g.Wc(this.Pb(),!0),g.Wj(function(){g.Mr(this.Pb(),"iv-promo-inactive")},100,this),this.Pb().removeAttribute("aria-hidden"),this.isActive=!0,Gyz(this),d9z(this),E_m(this,this.W))};
g.A.hide=function(){this.isActive&&(g.uG(this.Pb(),"iv-promo-inactive"),this.isActive=!1,this.Pb().setAttribute("aria-hidden","true"))};
g.A.sE=function(F,J,b,I,u,w){return this.isCollapsed?!1:wp.prototype.sE.call(this,F,J,b,I,u,w)};
g.A.TDv=function(F){this.Y=!0;fiW(this,500,F)};
g.A.UfN=function(){this.Y=!1;j0W(this)};
g.A.NA=function(F){F.stopPropagation();this.hide()};
g.A.IY=function(F){F.stopPropagation();Gyz(this);this.isCollapsed=!0;g.uG(this.Pb(),"iv-promo-collapsed-no-delay");this.D.start()};
g.A.destroy=function(){this.D.dispose();wp.prototype.destroy.call(this)};g.z(PwW,g.GN);g.A=PwW.prototype;g.A.qJ=function(F,J){if(!o_b(this.player.J().playerStyle))return null;switch(F){case "loadCustomAnnotationsXml":return(F=g.xv(J))&&s05(this,F),!0;case "removeCustomAnnotationById":return J&&this.C&&(uvt(this.C,J),VW(this.player)),!0}return null};
g.A.getOptions=function(){return o_b(this.player.J().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.A.X$=function(){var F=this.player.J(),J=this.player.getVideoData(),b=F.annotationsLoadPolicy||J.annotationsLoadPolicy;return g.tw(J)||this.player.isMutedByEmbedsMutedAutoplay()?!1:b===1&&!J.yC||F.fW.get(J.videoId)||g.BE(J)||g.Te(J)?!0:!1};
g.A.TN=function(){if(this.T){var F=this.player.mG().getVideoContentRect(!0);g.lu(this.T.element,F.width,F.height);g.yf(this.T.element,F.left,F.top)}if(this.C){var J=this.player.xK();F=this.C;J=J.width;g.qr(F.Z,"iv-drawer-small",J<=426);g.qr(F.Z,"iv-drawer-big",J>=1280)}};
g.A.lG=function(F){T3b(this,F.state);g.x(F.state,2)&&(this.AD()&&this.U0()&&this.player.getPresentingPlayerType()!==2&&this.Xs(!1),this.ZZ(!1))};
g.A.load=function(){function F(M){var q=J.loadNumber;J.D=null;J.loaded&&J.loadNumber===q&&J.player.getVideoData().videoId===I&&(M=g.Kl(M)&&M.responseXML?M.responseXML:null)&&(s05(J,M),g.uG(J.player.getRootNode(),"iv-module-loaded"))}
var J=this;g.GN.prototype.load.call(this);T3b(this,this.player.getPlayerStateObject());this.loadNumber++;var b=this.player.getVideoData(),I=b.videoId;g.Lw()&&(F=YQU(this,F));var u={format:"XML",onFinish:F,onError:function(){J.D=null},
urlParams:{}};b.isPharma&&(u.urlParams.pharma="1");u.method="POST";u.withCredentials=!0;var w=this.player.J().fW.get(I);w&&$9U(u,w);w=w&&(w.d4||w.Xj);if(!b.LI||w)b.Jz?rQm(this,b.Jz,u):(this.V=function(){if(!J.Y)J.onVideoDataChange(u);var M=J.player.getVideoData();(M==null?0:g.PE(M))&&!J.Tj&&RsW(J,M)},this.player.addEventListener("videodatachange",this.V));
g.Pp(this.player,this.T.element,4);this.TN();(w=g.BE(b))&&Q0R(this,w);(w=g.Te(b))&&w.featuredChannel&&O5z(this,w.featuredChannel,w.annotationId||"branding",b.videoId||null,b.eventId||null);this.EV=g.c1("ytp-cards-button",this.player.getRootNode());g.PE(b)&&RsW(this,b)};
g.A.onVideoDataChange=function(F){var J=this.player.getVideoData();J.Jz&&rQm(this,J.Jz,F)};
g.A.unload=function(){this.player.Yo("annotations_module");for(var F=g.N(Object.keys(this.W)),J=F.next();!J.done;J=F.next())this.W[J.value].destroy();this.N=null;this.C&&(this.C.destroy(),this.C=null,VW(this.player));this.Y=!1;this.D&&(this.D.abort(),this.D=null);this.Tj=!1;this.W={};this.U.hide();g.GN.prototype.unload.call(this);this.T.detach();this.V&&(this.player.removeEventListener("videodatachange",this.V),this.V=null)};
g.A.YP=function(F){F===this.player.getVideoData().videoId&&(this.loaded?Cwm(this):this.load())};
g.A.AD=function(){var F;return((F=this.C)==null?void 0:F.isAvailable())||this.Tj};
g.A.U0=function(){return!!this.C&&this.C.T};
g.A.Xs=function(F,J,b){J=J===void 0?!1:J;this.AD();this.C&&(F?b?H_(this.C,b,J):H_(this.C,"YOUTUBE_DRAWER_AUTO_OPEN",J):Lt(this.C))};
g.A.ZZ=function(F,J){this.player.publish(F?"cardsteasershow":"cardsteaserhide",J)};
g.A.X_=function(){this.player.J().fW.unsubscribe("vast_info_card_add",this.YP,this);g.Mr(this.player.getRootNode(),g.QA.IV_DRAWER_OPEN);for(var F=this.eE,J=g.D_,b=0,I=F.length;b<I;b++)J.q_(F[b]);this.eE.length=0;g.GN.prototype.X_.call(this)};
g.A.createElement=function(F){F=new g.U(F);g.k(this,F);return F.element};g.jn("annotations_module",PwW);g.jn("creatorendscreen",dXt);})(_yt_player);
