(function(g){var window=this;'use strict';var EVV=function(F,J){if(!Number.isFinite(F))return String(F);F=String(F);var b=F.indexOf(".");b===-1&&(b=F.length);var I=F[0]==="-"?"-":"";I&&(F=F.substring(1));return I+(0,g.jGk)("0",Math.max(0,J-b))+F},jce=function(){return{X:"svg",
L:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},j:[{X:"path",L:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},Gqt=function(){return{X:"svg",
L:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},j:[{X:"path",L:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},P5W=function(F){typeof F==="number"?(this.date=VPm(F,0,1),fs(this,1)):g.Um(F)?(this.date=VPm(F.getFullYear(),F.getMonth(),F.getDate()),fs(this,F.getDate())):(this.date=new Date(g.L3()),F=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),fs(this,F))},VPm=function(F,J,b){J=new Date(F,J,b);
F>=0&&F<100&&J.setFullYear(J.getFullYear()-1900);return J},fs=function(F,J){F.getDate()!=J&&F.date.setUTCHours(F.date.getUTCHours()+(F.getDate()<J?1:-1))},Wb=function(F,J){g.YJ.call(this,F,{X:"div",
K:"ytp-reminder-menu",L:{role:"menu",tabindex:"-1"},j:[{X:"div",K:"ytp-reminder-menu-contents",j:[{X:"div",K:"ytp-reminder-menu-items"}]}]},100,!0);this.C=J;this.T=[];this.menuPopupRenderer=void 0;this.items=this.RI("ytp-reminder-menu-items");this.hide()},Bbb=function(F){return(F.menuPopupRenderer&&F.menuPopupRenderer.items||[]).reduce(function(J,b){b&&b.menuServiceItemRenderer&&J.push(b.menuServiceItemRenderer);
return J},[])},dn=function(F){g.U.call(this,{X:"div",
j:[{X:"button",Dv:["ytp-offline-slate-button","ytp-button"],j:[{X:"div",K:"ytp-offline-slate-button-icon",sQ:"{{icon}}"},{X:"div",K:"ytp-offline-slate-button-text",sQ:"{{text}}"}]}]});this.G=F;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.U=void 0;this.Z=this.C=null;(this.W=this.RI("ytp-offline-slate-button"))&&this.B(this.W,"click",this.V);this.hide()},rz1=function(F,J,b){!F.toggleButtonRenderer&&J&&J.toggleButtonRenderer?F.toggleButtonRenderer=J.toggleButtonRenderer:
J&&J.toggleButtonRenderer||(F.toggleButtonRenderer=null);
!F.upcomingEventReminderButtonRenderer&&b&&g.O(b,Tb8)?F.upcomingEventReminderButtonRenderer=g.O(b,Tb8):b&&g.O(b,Tb8)||(F.upcomingEventReminderButtonRenderer=null);EA(F)},EA=function(F){if(F.toggleButtonRenderer){var J=F.toggleButtonRenderer;
if(J.isToggled){var b=J.toggledText?g.Kr(J.toggledText):"";F.update({text:b,icon:Ssk(J.toggledIcon)})}else b=J.defaultText?g.Kr(J.defaultText):"",F.update({text:b,icon:Ssk(J.defaultIcon)});F.show()}else F.upcomingEventReminderButtonRenderer?(J=scU(F))?(b=J.text?g.Kr(J.text):"",F.update({text:b,icon:Ssk(J.icon)}),F.show()):F.hide():F.hide()},$fe=function(F,J,b){F.Z||(F.Z=new g.tB(F.G.J().wX));
var I={context:g.vr(F.Z.config_||g.qK())};g.W8()&&(I.context.clientScreenNonce=g.W8());I.params=b;g.ZD(F.Z,J,I,{timeout:5E3,onSuccess:function(){F.upcomingEventReminderButtonRenderer&&F.U&&(F.upcomingEventReminderButtonRenderer.currentState=F.U,F.U=void 0)},
onError:function(){Yst(F)},
onTimeout:function(){Yst(F)}})},Yst=function(F){F.toggleButtonRenderer?(F.toggleButtonRenderer.isToggled=!F.toggleButtonRenderer.isToggled,EA(F)):F.upcomingEventReminderButtonRenderer&&(F.U=void 0,EA(F))},Ssk=function(F){if(!F)return null;
switch(F.iconType){case "NOTIFICATIONS":return jce();case "NOTIFICATIONS_NONE":return Gqt();case "NOTIFICATIONS_ACTIVE":return g.lA();default:return null}},scU=function(F){if(!F.upcomingEventReminderButtonRenderer)return null;
var J=F.U||F.upcomingEventReminderButtonRenderer.currentState;F=g.N(F.upcomingEventReminderButtonRenderer.states||[]);for(var b=F.next();!b.done;b=F.next())if((b=g.O(b.value,C55))&&b.state===J&&b.button&&g.O(b.button,g.TX))return g.O(b.button,g.TX);return null},XjW=function(F){g.U.call(this,{X:"div",
K:"ytp-offline-slate",j:[{X:"div",K:"ytp-offline-slate-background"},{X:"div",K:"ytp-offline-slate-bar",j:[{X:"span",K:"ytp-offline-slate-icon",j:[{X:"svg",L:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},j:[{X:"path",L:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{X:"circle",L:{cx:"12",cy:"12",r:"3"}}]}]},{X:"span",K:"ytp-offline-slate-messages",j:[{X:"div",K:"ytp-offline-slate-main-text",L:{"aria-label":"{{label}}"},sQ:"{{mainText}}"},{X:"div",K:"ytp-offline-slate-subtitle-text",sQ:"{{subtitleText}}"}]},{X:"span",K:"ytp-offline-slate-buttons"}]},{X:"button",Dv:["ytp-offline-slate-close-button","ytp-button"],j:[g.yr()]},{X:"button",Dv:["ytp-offline-slate-open-button","ytp-button"],j:[g.mh()]}]});var J=this;this.api=F;this.C=this.U=null;this.background=this.RI("ytp-offline-slate-background");
this.T=this.RI("ytp-offline-slate-bar");this.W=new g.ty(function(){g.uG(J.T,"ytp-offline-slate-bar-fade")},15E3);
this.V=!1;this.Z=new g.ty(function(){g.uG(J.element,"ytp-offline-slate-collapsed")},15E3);
g.k(this,this.Z);g.k(this,this.W);this.countdownTimer=new g.ty(this.kX,1E3,this);this.B(F,"presentingplayerstatechange",this.qB);this.B(F,"livestatedata",this.VG);this.B(this.RI("ytp-offline-slate-close-button"),"click",function(){g.uG(J.element,"ytp-offline-slate-collapsed")});
this.B(this.RI("ytp-offline-slate-open-button"),"click",function(){g.Mr(J.element,"ytp-offline-slate-collapsed")});
this.hide();F=this.getVideoData();F.getPlayerResponse()&&(F=F.getPlayerResponse().playabilityStatus)&&this.VG(F);F=this.api.getPresentingPlayerType()===8&&!this.getVideoData().Mh;var b=this.api.getPresentingPlayerType()===8;g.qr(this.element,"ytp-offline-slate-premiere-trailer",F);g.qr(this.element,"ytp-offline-slate-hide-background",b)},QcV=function(F,J,b){if(J){var I=J.subtitleText!=null?g.Kr(J.subtitleText):"";
b=b?b:J.mainText!=null?g.Kr(J.mainText):"";var u,w,M,q;J=(q=(u=J.mainText)==null?void 0:(w=u.accessibility)==null?void 0:(M=w.accessibilityData)==null?void 0:M.label)!=null?q:b;F.update({mainText:b,subtitleText:I,label:J});g.qr(F.element,"ytp-offline-slate-single-text-line",!I);g.qr(F.T,"ytp-offline-slate-bar-hidden",!b&&!I)}},jF=function(F,J){var b=(0,g.jR)();
this.module="heartbeat";this.trigger=F;this.C=J;this.T=b},hBR=function(F){g.GN.call(this,F);
var J=this;this.V=!1;this.Y=0;this.D=!1;this.U=new g.ty(function(){RBV(J)},0);
this.C=this.heartbeatParams=null;this.Z=!1;this.W=new g.Wz(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.Tj=new g.tB(void 0);this.attestationResponse=Promise.resolve(void 0);this.N=Promise.resolve(void 0);this.utcOffsetMinutes=-(new P5W).getTimezoneOffset();this.T=new g.s5(this);g.k(this,this.U);g.k(this,this.T);DfR(this);kqt(this);this.T.B(F,"heartbeatparams",this.Nq);this.T.B(F,"presentingplayerstatechange",this.JS);this.T.B(F,"videoplayerreset",this.yy);this.T.B(F,g.u6("heartbeat"),
this.onCueRangeEnter);this.Z&&this.C&&Ou5(this,void 0,this.C);var b=new g.b6(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),I=new g.b6(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});F.TU([b,I]);oVL(this)},oVL=function(F){var J=F.getVideoData();
!J.S("use_rta_for_player")&&J.us&&(J=J.botguardData)&&g.TR(J,F.player.J())},czW=function(F){var J,b;
return g.S(function(I){if(I.C==1)return g.T(I,g.EBG(),2);if(!I.U)return F.sequenceNumber>=3?I.return({error:"ATTESTATION_ERROR_VM_INTERNAL_ERROR"}):I.return(void 0);J=F.getVideoData();b={};return I.return(g.dq3((b.cpn=J.clientPlaybackNonce,b.encryptedVideoId=J.videoId||"",b),1500))})},DfR=function(F){var J=F.getVideoData();
if(J.us)if(J.S("use_rta_for_player"))F.attestationResponse=czW(F);else if(J=new g.lY7(J),g.GR.isInitialized()||F.sequenceNumber>=3){var b=Promise,I=b.resolve,u=null;if(J.videoData.vQ){var w=g.fY7(J);if(w){u={};var M={};w=w.split("&");w=g.N(w);for(var q=w.next();!q.done;q=w.next())q=q.value.split("="),q.length===2&&(M[q[0]]=q[1]);M.r1a&&(u.webResponse=M.r1a);M.r1c&&(u.error=Ufk[Number(M.r1c)]);u.challenge=J.videoData.vQ}}F.attestationResponse=I.call(b,u||void 0)}},xfR=function(F){var J=F.getVideoData();
if(!g.yR(F.getVideoData())||J.Xp)return!1;if(J.D){F=J.D.flavor==="playready"&&J.S("html5_innertube_heartbeats_for_playready");var b=J.D.flavor==="widevine"&&J.S("html5_innertube_heartbeats_for_widevine");J=g.sD(J.D)&&J.S("html5_innertube_heartbeats_for_fairplay");return!(F||b||J)}return!0},nV5=function(F){if(xfR(F))return!!F.heartbeatParams;
var J=F.getVideoData();return!g.yR(F.getVideoData())||J.PS||J.Au?!!J.heartbeatToken:!1},GY=function(F,J){if(!F.U.isActive()&&F.V){var b=F.getVideoData();
if(nV5(F)||b.isLivePlayback){if(J===void 0)if(F.D)if(F.Z)J=7500;else{var I;J=((I=F.heartbeatParams)==null?0:I.interval)?F.heartbeatParams.interval*1E3:F.getVideoData().u_||6E4}else J=1E3;F.U.start(J)}}},LIb=function(F,J,b){J.jn&&(b=g.Os(b,{internalipoverride:J.jn}));
var I={cpn:J.clientPlaybackNonce};J.contextParams&&(I.context_params=J.contextParams);J.Um&&(I.kpt=J.Um);b=g.Os(b,I);g.E6(b,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(u){if(!F.U.isActive()&&VQ(F)){F.W.reset();F.sequenceNumber++;u=u.responseText;var w=tPm(u);if(w){F.player.jE("onHeartbeat",w);var M=w.status==="ok"?w.stop_heartbeat?2:0:w.status==="stop"?1:w.status==="live_stream_offline"?0:-1}else M=(M=u.match(Zuz))?M[1]==="0"?0:1:-1;HuV(F,void 0,w,u,M)}},
onError:function(u){VQ(F)&&Pb(F,!0,"net-"+u.status)},
onTimeout:function(){VQ(F)&&Pb(F,!0,"timeout")},
withCredentials:!0})},RBV=function(F){var J,b;
g.S(function(I){J=F.player.J();b=F.getVideoData();if(!VQ(F))return I.return();if(xfR(F))return F6b(F,J,b),I.gD(0);DfR(F);return g.T(I,Jvk(F,J,b),0)})},F6b=function(F,J,b){var I;
if((I=F.heartbeatParams)!=null&&I.url){var u=g.Os(F.heartbeatParams.url,{request_id:g.B$k()});b.eE&&(u=g.Os(u,{vvt:b.eE}),b.mdxEnvironment&&(u=g.Os(u,{mdx_environment:b.mdxEnvironment})));g.LH(J,b.oauthToken).then(function(w){w&&(u=g.Os(u,{access_token:w}));LIb(F,b,u)})}},VQ=function(F){var J=F.getVideoData();
return F.player.getPresentingPlayerType()===3||g.x(F.player.getPlayerStateObject(F.getPlayerType()),4)?!1:nV5(F)||J.isLivePlayback?!0:(Bb(F),!1)},Jvk=function(F,J,b){var I,u,w,M,q,v,a,e,K,p,m,y,f,d,G,P,r,Q,D,t;
return g.S(function(n){if(n.C==1)return I="player/heartbeat",w={videoId:b.videoId,sequenceNumber:F.sequenceNumber,heartbeatServerData:(u=F.eE)!=null?u:b.heartbeatServerData},F.N=F.attestationResponse,b.us?g.T(n,F.N,3):n.gD(2);n.C!=2&&(w.attestationResponse=n.U);M=g.FE(b);v=(q=M.client)!=null?q:{};v.utcOffsetMinutes=F.utcOffsetMinutes;w.context=M;w.cpn=b.clientPlaybackNonce;if(a=typeof Intl!=="undefined"?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)v.timeZone=a;e={heartbeatChecks:[]};
if(K=b.getPlayerResponse())b.heartbeatToken&&(w.heartbeatToken=b.heartbeatToken),(p=K.playabilityStatus)&&(m=p.liveStreamability)&&m.liveStreamabilityRenderer&&e.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");b.heartbeatToken&&e.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");g.dX(J)&&(e.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED"),y=b2e(F),f={},y!==null&&(f.clientPlayerPositionUtcMillis=y),G=(d=F.player.TF())==null?void 0:g.Ql(d),r=((P=G)==null?void 0:P.freePreviewWatchedDuration)||
0,r>0&&(f.freePreviewWatchedDuration={seconds:""+r}),e.unpluggedParams=f);w.heartbeatRequestParams=e;b.isLivePlayback?(Q=b2e(F),Q!==null&&(w.playbackState||(w.playbackState={}),w.playbackState.playbackPosition={utcTimeMillis:Q})):J.S("enable_heartbeat_vod_playback_position")&&(D=IF1(F),D!==null&&(w.playbackState||(w.playbackState={}),w.playbackState.playbackPosition={streamTimeMillis:D}));F.player.publish("heartbeatRequest",w);t={timeout:3E4,onSuccess:function(uk){if(!F.U.isActive()&&VQ(F)){var AJ=
F.getVideoData(),F7=AJ.us&&F.N==null,h;AJ.us=!((h=uk.heartbeatAttestationConfig)==null||!h.requiresAttestation)||F7;F7=uk.playabilityStatus;h=JSON.stringify(F7)||"{}";uk.authenticationMismatch&&F.player.UQ("authshear",{});var L=-1;var l=uk.playabilityStatus;l&&(F.player.jE("onHeartbeat",l),l.status==="OK"?L=uk.stopHeartbeat?2:0:l.status==="UNPLAYABLE"?L=1:l.status==="LIVE_STREAM_OFFLINE"&&(L=0));F.sequenceNumber&&L===-1||F.W.reset();F.sequenceNumber++;uk.heartbeatServerData&&(F.eE=uk.heartbeatServerData);
AJ.nx=uk;(l=uk.playerCueRangeSet)&&g.cC(AJ,l);uk.playerCueRanges&&uk.playerCueRanges.length>0&&(AJ.cueRanges=uk.playerCueRanges);var c,Da;((c=uk.progressBarConfig)==null?0:c.progressBarStartPosition)&&((Da=uk.progressBarConfig)==null?0:Da.progressBarEndPosition)&&(AJ.progressBarStartPosition=uk.progressBarConfig.progressBarStartPosition,AJ.progressBarEndPosition=uk.progressBarConfig.progressBarEndPosition);AJ.compositeLiveIngestionOffsetToken=uk.compositeLiveIngestionOffsetToken;uk.compositeLiveStatusToken!==
AJ.compositeLiveStatusToken&&(AJ.compositeLiveStatusToken=uk.compositeLiveStatusToken);AJ.publish("dataupdated");HuV(F,uk,F7,h,L)}},
onError:function(uk){VQ(F)&&Pb(F,!0,"net-"+uk.status)},
onTimeout:function(){VQ(F)&&Pb(F,!0,"timeout")}};
g.LH(J,g.ks(b)).then(function(uk){uk&&(t.C0="Bearer "+uk);g.ZD(F.Tj,I,w,t)});
g.N4(n)})},HuV=function(F,J,b,I,u){u===-1?(b="decode "+g.NL(I,3),Pb(F,!1,b)):u===2?(Bb(F),F.D=!0):(F.Y=0,F.U.stop(),u===1?(F.D=!1,b&&b.errorCode==="PLAYABILITY_ERROR_CODE_EMBARGOED"&&F.player.rT(!0),u="pe."+(b==null?void 0:b.errorCode)+";ps."+(b==null?void 0:b.status),F.player.Je("heartbeat.stop",2,F.Aw(I),u),g.AY("heartbeatActionPlayerHalted",u5z(b)),(J==null?0:J.videoTransitionEndpoint)&&b&&(J=J.videoTransitionEndpoint,(I=g.O(J,g.x$))&&wRt(F,I,b,{itct:J==null?void 0:J.clickTrackingParams}))):(F.D=
!0,I=0,F.Z&&b&&(I=Ou5(F,J,b),F.player.publish("livestatedata",b)),I?GY(F,I):GY(F)))},Ou5=function(F,J,b){var I=b.liveStreamability&&b.liveStreamability.liveStreamabilityRenderer,u=!(!I||!(I.switchStreamsImmediately||I.transitionTiming&&I.transitionTiming==="STREAM_TRANSITION_TIMING_IMMEDIATELY"));
J=MW1(F,J,I);var w=F.getVideoData(),M=F.player.getPlayerStateObject(F.getPlayerType()),q=M.isPlaying()&&!g.dS(w)&&!F.player.isAtLiveHead(F.getPlayerType());if(w.J().hJ()){var v,a=((v=F.player.Qa())==null?void 0:v.Cy())||{};a.status=b.status||"";a.dvr=""+ +q;a["switch"]=""+ +u;a.ended=""+ +!(!I||!I.displayEndscreen);F.player.UQ("heartbeat",a)}if(q&&!u)return J;u=I&&I.streamTransitionEndpoint&&g.O(I.streamTransitionEndpoint,g.x$);if((I&&I.transitionTiming)==="STREAM_TRANSITION_TIMING_AT_STREAM_END")F.getVideoData().transitionEndpointAtEndOfStream=
u;else if(u&&wRt(F,u,b))return J;if(b.status.toUpperCase()==="OK"){u=I&&I.broadcastId;v=F.C&&F.C.liveStreamability&&F.C.liveStreamability.liveStreamabilityRenderer&&F.C.liveStreamability.liveStreamabilityRenderer.broadcastId;q=u!==v&&u!=null;if(!g.lE(w)||q){var e={video_id:w.videoId};w.UP&&(e.is_live_destination="1");F.player.S("web_player_heartbeat_request_watch_next")||(e.disable_watch_next=!0,e.raw_watch_next_response=w.getWatchNextResponse());e.autonav_state=w.autonavState;e.oauth_token=w.oauthToken;
e.force_gvi=w.Ys;e.bB=w.bB;w.W&&(e.vss_credentials_token=w.W,e.vss_credentials_token_type=w.kZ);w.eE&&(e.vvt=w.eE);I=void 0;g.lE(w)?q&&(I=new jF("broadcastIdChanged",v+","+u),F.eC("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",b)):(u&&(I=new jF("formatsReceived",""+u)),F.eC("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",b));F.player.loadVideoByPlayerVars(e,void 0,void 0,void 0,I);return J}F.player.d6("heartbeat",
F.getPlayerType())}I&&I.displayEndscreen&&(F.offlineSlate?(F=F.offlineSlate,F.V=!0,F.uT&&F.api.Pp()):M.isBuffering()&&(w=((e=F.player.Qa())==null?void 0:e.Cy())||{},F.player.UQ("hbse",w,!0),F.player.Pp(),F.player.jE("onLiveMediaEnded",b)));return J},MW1=function(F,J,b){return F.player.S("web_player_use_heartbeat_poll_delay_ms")&&(F=Number(J==null?void 0:J.pollDelayMs))?F:(b=Number(b==null?void 0:b.pollDelayMs))?b:0},Pb=function(F,J,b){var I=F.player.J();
if(!F.U.isActive()){F.U.stop();F.Y++;var u=J?"heartbeat.net":"heartbeat.servererror";var w=F.getVideoData();if(w.Bw||J&&!g.yR(F.getVideoData())&&!nV5(F)&&w.isLivePlayback)w=!1;else{var M,q;((q=F.heartbeatParams)==null?0:q.retries)?M=F.heartbeatParams.retries:M=w.Fl||5;w=F.Y>=M}w?(g.AY("heartbeatActionPlayerHalted",J?{enforcedPolicyToHaltOnNetworkFailure:!0}:u5z()),(J=F.getVideoData())&&J.isLivePlayback?F.player.Je(u,1,"Video oynat\u0131m\u0131 kesildi. L\u00fctfen tekrar deneyin.",b):F.player.Je(u,
1,"Maalesef bu videonun lisanslanmas\u0131nda bir hata olu\u015ftu.",b)):(I.S("html5_report_non_fatal_heartbeat_error")&&F.player.Nb(u,{msg:b}),GY(F,F.W.getValue()),g.dK(F.W))}},u5z=function(F){var J={enforcedPolicyToHaltOnNetworkFailure:!1};
F&&(J.serializedServerContext=F.additionalLoggingData);return J},Bb=function(F){F.Y=0;
F.U.stop();F.D=!1;F.sequenceNumber=0},kqt=function(F){var J=F.getVideoData(),b=F.player.J();
if(J.isLivePlayback)if(g.HG(b.D)){F.Z=!0;F.V=!0;if(!g.jB(b)||g.dX(b))F.offlineSlate=new XjW(F.player),g.k(F,F.offlineSlate),g.Pp(F.player,F.offlineSlate.element,4);(J=J.getPlayerResponse())&&J.playabilityStatus&&(F.C=J.playabilityStatus);var I;((I=F.C)==null?void 0:I.status)!=="UNPLAYABLE"&&(F.C?(I=MW1(F,void 0,F.C.liveStreamability&&F.C.liveStreamability.liveStreamabilityRenderer))?GY(F,I):GY(F,7500):GY(F,1E3))}else F.player.Je("html5.unsupportedlive",2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");
else g.te(J.kQ,"heartbeat")&&F.player.d6("heartbeat",F.getPlayerType())},wRt=function(F,J,b,I){var u=J&&J.videoId;
return u?(F.player.yp(u,Object.assign({},{autonav:"1"},I||{}),void 0,!0,!0,J,g.ks(F.getVideoData())),F.eC("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",b),!0):!1},b2e=function(F){return(F=F.player.getProgressState(F.getPlayerType()).ingestionTime)&&isFinite(F)?""+Math.floor(F*1E3):null},IF1=function(F){return(F=F.player.getCurrentTime(F.getPlayerType()))&&isFinite(F)?""+Math.floor(F*1E3):null},tPm=function(F){try{var J=JSON.parse(F);
return J!=null?J:void 0}catch(b){}},AvU={ERAS:["BC",
"AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};
AvU={ERAS:["M\u00d6","MS"],ERANAMES:["Milattan \u00d6nce","Milattan Sonra"],NARROWMONTHS:"O\u015eMNMHTAEEKA".split(""),STANDALONENARROWMONTHS:"O\u015eMNMHTAEEKA".split(""),MONTHS:"Ocak \u015eubat Mart Nisan May\u0131s Haziran Temmuz A\u011fustos Eyl\u00fcl Ekim Kas\u0131m Aral\u0131k".split(" "),STANDALONEMONTHS:"Ocak \u015eubat Mart Nisan May\u0131s Haziran Temmuz A\u011fustos Eyl\u00fcl Ekim Kas\u0131m Aral\u0131k".split(" "),SHORTMONTHS:"Oca \u015eub Mar Nis May Haz Tem A\u011fu Eyl Eki Kas Ara".split(" "),
STANDALONESHORTMONTHS:"Oca \u015eub Mar Nis May Haz Tem A\u011fu Eyl Eki Kas Ara".split(" "),WEEKDAYS:"Pazar Pazartesi Sal\u0131 \u00c7ar\u015famba Per\u015fembe Cuma Cumartesi".split(" "),STANDALONEWEEKDAYS:"Pazar Pazartesi Sal\u0131 \u00c7ar\u015famba Per\u015fembe Cuma Cumartesi".split(" "),SHORTWEEKDAYS:"Paz Pzt Sal \u00c7ar Per Cum Cmt".split(" "),STANDALONESHORTWEEKDAYS:"Paz Pzt Sal \u00c7ar Per Cum Cmt".split(" "),NARROWWEEKDAYS:"PPS\u00c7PCC".split(""),STANDALONENARROWWEEKDAYS:"PPS\u00c7PCC".split(""),
SHORTQUARTERS:["\u00c71","\u00c72","\u00c73","\u00c74"],QUARTERS:["1. \u00e7eyrek","2. \u00e7eyrek","3. \u00e7eyrek","4. \u00e7eyrek"],AMPMS:["\u00d6\u00d6","\u00d6S"],DATEFORMATS:["d MMMM y EEEE","d MMMM y","d MMM y","d.MM.y"],TIMEFORMATS:["HH:mm:ss zzzz","HH:mm:ss z","HH:mm:ss","HH:mm"],DATETIMEFORMATS:["{1} {0}","{1} {0}","{1} {0}","{1} {0}"],FIRSTDAYOFWEEK:0,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:6};
var Ufk=["ATTESTATION_ERROR_UNKNOWN","ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"],qUW={300:"STREAMING_DEVICES_QUOTA_PER_24H_EXCEEDED",301:"ALREADY_PINNED_ON_A_DEVICE",303:"STOPPED_BY_ANOTHER_PLAYBACK",304:"TOO_MANY_STREAMS_PER_USER",305:"TOO_MANY_STREAMS_PER_ENTITLEMENT",400:"VIDEO_NOT_FOUND",401:"GEO_FAILURE",402:"STREAMING_NOT_ALLOWED",403:"UNSUPPORTED_DEVICE",405:"VIDEO_FORBIDDEN",500:"PURCHASE_NOT_FOUND",
501:"RENTAL_EXPIRED",502:"PURCHASE_REFUNDED",5E3:"BAD_REQUEST",5001:"CGI_PARAMS_MISSING",5002:"CGI_PARAMS_MALFORMED",5100:"AUTHENTICATION_MISSING",5101:"AUTHENTICATION_MALFORMED",5102:"AUTHENTICATION_EXPIRED",5200:"CAST_TOKEN_MALFORMED",5201:"CAST_TOKEN_EXPIRED",5202:"CAST_TOKEN_FAILED",5203:"CAST_SESSION_VIDEO_MISMATCHED",5204:"CAST_SESSION_DEVICE_MISMATCHED",6E3:"INVALID_DRM_MESSAGE",7E3:"SERVER_ERROR",8E3:"RETRYABLE_ERROR"};g.A=P5W.prototype;g.A.gR=AvU.FIRSTDAYOFWEEK;g.A.WX=AvU.FIRSTWEEKCUTOFFDAY;
g.A.clone=function(){var F=new P5W(this.date);F.gR=this.gR;F.WX=this.WX;return F};
g.A.getFullYear=function(){return this.date.getFullYear()};
g.A.getYear=function(){return this.getFullYear()};
g.A.getMonth=function(){return this.date.getMonth()};
g.A.getDate=function(){return this.date.getDate()};
g.A.getTime=function(){return this.date.getTime()};
g.A.getDay=function(){return this.date.getDay()};
g.A.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.A.getUTCMonth=function(){return this.date.getUTCMonth()};
g.A.getUTCDate=function(){return this.date.getUTCDate()};
g.A.getUTCDay=function(){return this.date.getDay()};
g.A.getUTCHours=function(){return this.date.getUTCHours()};
g.A.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.A.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.A.set=function(F){this.date=new Date(F.getFullYear(),F.getMonth(),F.getDate())};
g.A.setFullYear=function(F){this.date.setFullYear(F)};
g.A.setYear=function(F){this.setFullYear(F)};
g.A.setMonth=function(F){this.date.setMonth(F)};
g.A.setDate=function(F){this.date.setDate(F)};
g.A.setTime=function(F){this.date.setTime(F)};
g.A.setUTCFullYear=function(F){this.date.setUTCFullYear(F)};
g.A.setUTCMonth=function(F){this.date.setUTCMonth(F)};
g.A.setUTCDate=function(F){this.date.setUTCDate(F)};
g.A.add=function(F){if(F.years||F.months){var J=this.getMonth()+F.months+F.years*12,b=this.getYear()+Math.floor(J/12);J%=12;J<0&&(J+=12);a:{switch(J){case 1:var I=b%4!=0||b%100==0&&b%400!=0?28:29;break a;case 5:case 8:case 10:case 3:I=30;break a}I=31}I=Math.min(I,this.getDate());this.setDate(1);this.setFullYear(b);this.setMonth(J);this.setDate(I)}F.days&&(b=this.getYear(),J=b>=0&&b<=99?-1900:0,F=new Date((new Date(b,this.getMonth(),this.getDate(),12)).getTime()+F.days*864E5),this.setDate(1),this.setFullYear(F.getFullYear()+
J),this.setMonth(F.getMonth()),this.setDate(F.getDate()),fs(this,F.getDate()))};
g.A.Hg=function(F){return!(!F||this.getYear()!=F.getYear()||this.getMonth()!=F.getMonth()||this.getDate()!=F.getDate())};
g.A.toString=function(){var F=this.getFullYear(),J=F<0?"-":F>=1E4?"+":"";return[J+EVV(Math.abs(F),J?6:4),EVV(this.getMonth()+1,2),EVV(this.getDate(),2)].join("")+""};
g.A.valueOf=function(){return this.date.valueOf()};var v9L=new g.Ek("addUpcomingEventReminderEndpoint");var aFV=new g.Ek("removeUpcomingEventReminderEndpoint");var eP8=new g.Ek("updateUpcomingEventReminderButtonStateCommand");var Tb8=new g.Ek("upcomingEventReminderButtonRenderer"),C55=new g.Ek("upcomingEventReminderButtonStateRenderer");g.z(Wb,g.YJ);
Wb.prototype.updateMenuItems=function(){var F=this,J=Bbb(this),b=0;b=0;for(var I={};b<J.length;I={xt:void 0},b++){var u=this.T[b];u||(u=new g.U({X:"div",K:"ytp-reminder-menu-item",L:{role:"menuitem",tabindex:"0"},j:[{X:"div",K:"ytp-reminder-menu-item-icon",sQ:"{{icon}}"},{X:"div",K:"ytp-reminder-menu-item-label",sQ:"{{text}}"}]}),I.xt=b,u.listen("click",function(M){return function(){var q=M.xt;F.fk();q=Bbb(F)[q];F.publish("reminderMenuItemClicked",q.serviceEndpoint||q.command)}}(I)),u.Az(this.items),
this.T[b]=u);
var w=J[b];I=null;switch(w.icon&&w.icon.iconType){case "NOTIFICATIONS":I=jce();break;case "NOTIFICATIONS_NONE":I=Gqt();break;case "NOTIFICATIONS_ACTIVE":I=g.lA()}w=w.text?g.Kr(w.text):"";u.update({icon:I,text:w})}for(;b<this.T.length;)this.T.pop().dispose();b===0?this.fk():this.Bo(this.C)};
Wb.prototype.hide=function(){this.C&&this.C.removeAttribute("aria-haspopup");g.YJ.prototype.hide.call(this)};
Wb.prototype.show=function(){this.C&&this.C.setAttribute("aria-haspopup","true");g.YJ.prototype.show.call(this)};
Wb.prototype.X_=function(){g.vk(this.T);g.YJ.prototype.X_.call(this)};g.z(dn,g.U);
dn.prototype.V=function(){if(this.toggleButtonRenderer){var F=this.toggleButtonRenderer;F.isToggled?this.T(F.toggledServiceEndpoint):this.T(F.defaultServiceEndpoint);F.isToggled=!F.isToggled;EA(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.C&&this.C.uT)this.C.fk();else{var J=scU(this);J&&this.T(J.serviceEndpoint||J.command);J=((F=g.O(J==null?void 0:J.command,g.p0))==null?void 0:F.commands)||[];a:{F=g.N(J);for(var b=F.next();!b.done;b=F.next()){var I=J=void 0;if(b=(J=g.O(b.value,g.XkV))==
null?void 0:(I=J.popup)==null?void 0:I.menuPopupRenderer){F=b;break a}}F=void 0}this.C||(this.C=new Wb(this.G,this.W),this.C.Az(this.element),g.k(this,this.C),this.C.subscribe("reminderMenuItemClicked",this.T,this));J=this.C;J.menuPopupRenderer=F;J.updateMenuItems()}};
dn.prototype.T=function(F){var J=g.O(F,v9L),b=g.O(F,aFV);if(F&&(J||b)){if(J){var I=J;var u="notification/add_upcoming_event_reminder"}else b&&(I=b,u="notification/remove_upcoming_event_reminder");if(u&&I&&I.params)for($fe(this,u,I.params),F=g.N(I.commands||[]),J=F.next();!J.done;J=F.next())if((J=J.value)&&g.O(J,eP8)){this.U=g.O(J,eP8).state;EA(this);break}}};g.z(XjW,g.U);g.A=XjW.prototype;g.A.getPlayerType=function(){if(this.api.getPresentingPlayerType()===8)return 1};
g.A.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.A.VG=function(F){var J,b,I=F==null?void 0:(J=F.liveStreamability)==null?void 0:(b=J.liveStreamabilityRenderer)==null?void 0:b.offlineSlate;if(I){this.U=F;J=I.liveStreamOfflineSlateRenderer;J.canShowCountdown?this.kX():QcV(this,J);var u,w,M,q;if(b=F==null?void 0:(u=F.liveStreamability)==null?void 0:(w=u.liveStreamabilityRenderer)==null?void 0:(M=w.offlineSlate)==null?void 0:(q=M.liveStreamOfflineSlateRenderer)==null?void 0:q.thumbnail){u=0;w=null;M=b.thumbnails;for(q=0;q<M.length;q++)M[q].width>
u&&(u=M[q].width||0,w=M[q].url);w&&(this.background.style.backgroundImage="url("+w+")")}else this.background.style.backgroundImage="";J.actionButtons||J.reminderButton?(this.C||(this.C=new dn(this.api),this.C.Az(this.RI("ytp-offline-slate-buttons")),g.k(this,this.C)),rz1(this.C,J.actionButtons&&J.actionButtons[0],J.reminderButton)):this.C&&rz1(this.C,null,null);this.U=F}else this.U=null;this.qB()};
g.A.qB=function(F){if(this.api.getPresentingPlayerType()===8)var J=!0;else{var b=this.api.getPlayerStateObject(),I=this.getVideoData();J=I.isLivePlayback&&(b.isBuffering()||g.x(b,2)||g.x(b,64));var u=I.autonavState===2&&g.x(b,2);b=b.isPlaying()&&!g.dS(I)&&!this.api.isAtLiveHead(void 0,!0);J=J&&!b&&!u}J&&this.U?this.uT?(F==null?0:g.e1(F,2))&&!this.getVideoData().Mh&&(g.Mr(this.element,"ytp-offline-slate-collapsed"),this.Z.stop(),g.Mr(this.T,"ytp-offline-slate-bar-fade"),this.W.start()):(this.show(),
this.Z.start(),this.api.publish("offlineslatestatechange"),this.V&&this.api.Pp()):this.uT&&(this.hide(),this.api.publish("offlineslatestatechange"))};
g.A.kX=function(){var F,J,b,I,u=(F=this.U)==null?void 0:(J=F.liveStreamability)==null?void 0:(b=J.liveStreamabilityRenderer)==null?void 0:(I=b.offlineSlate)==null?void 0:I.liveStreamOfflineSlateRenderer;u&&(F=Math.floor(g.L3()/1E3),J=u.canShowCountdown&&Number(u.scheduledStartTime),!J||J<=F?(QcV(this,u),this.countdownTimer.stop()):(QcV(this,u,g.lD(J-F)),g.Z_(this.countdownTimer)))};
g.A.X_=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.U.prototype.X_.call(this)};jF.prototype.U=function(F){return this.trigger&&F.trigger?this.module===F.module&&this.trigger===F.trigger&&this.C===F.C:!1};
jF.prototype.isExpired=function(){return(0,g.jR)()-this.T>6E4};
jF.prototype.toString=function(){return this.module+":"+this.trigger+":"+this.C};g.z(hBR,g.GN);g.A=hBR.prototype;g.A.X_=function(){Bb(this);this.player.Yo("heartbeat");g.GN.prototype.X_.call(this)};
g.A.onCueRangeEnter=function(){this.V=!0;GY(this,2E3)};
g.A.Nq=function(F){this.heartbeatParams=F;GY(this,2E3)};
g.A.JS=function(F){var J;this.player.getPresentingPlayerType()!==8&&((J=this.C)==null?void 0:J.status)!=="UNPLAYABLE"&&(g.x(F.state,2)||g.x(F.state,64)?(Bb(this),this.Z&&(this.V=!0,GY(this,1E3))):(g.x(F.state,1)||g.x(F.state,8))&&GY(this,2E3))};
g.A.yy=function(){this.player.getPresentingPlayerType()!==3&&GY(this,2E3)};
g.A.getPlayerType=function(){if(this.player.getPresentingPlayerType()===8)return 1};
g.A.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.A.u7=function(F){switch(F){case 4:case 3:return!1}return!0};
g.A.eC=function(F,J,b){F={trigger:F,reason:J};b&&(F.serializedServerContext=b.additionalLoggingData);g.AY("heartbeatActionPlayerTransitioned",F)};
g.A.Aw=function(F){var J="LICENSE",b=tPm(F);if(b)return b.reason||g.nV[J]||"";if(F=F.match(Zuz))if(F=Number(F[1]))J=(J=qUW[F.toString()])?J:"LICENSE";return g.nV[J]||""};
g.A.G9=function(){return!!this.offlineSlate&&this.offlineSlate.uT};
var Zuz=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.jn("heartbeat",hBR);})(_yt_player);
